/* Shared Admin / Agency demo export popover. Never creates or downloads files. */
(function(root){
  'use strict';let menu,trigger;
  function close(){if(menu)menu.remove();menu=null;if(trigger)trigger.setAttribute('aria-expanded','false');trigger=null;}
  function notify(text){if(root.mockExportNotify)return root.mockExportNotify(text);if(root.YuushiWorkflow)return root.YuushiWorkflow.notify(text);if(root.Toast?.ok)return root.Toast.ok(text);if(typeof root.toast==='function')return root.toast(text);if(typeof root.showToast==='function')return root.showToast(text,'success');const t=document.createElement('div');t.role='status';t.textContent=text;t.style.cssText='position:fixed;bottom:24px;right:24px;padding:12px 18px;border-radius:8px;background:var(--text-main,#3b2f2a);color:white;z-index:30000;font:inherit';document.body.append(t);setTimeout(()=>t.remove(),3200);}
  function open(button,prepare){if(menu&&trigger===button){close();return;}close();trigger=button;button.setAttribute('aria-expanded','true');button.setAttribute('aria-haspopup','menu');menu=document.createElement('div');menu.role='menu';menu.className='mock-export-menu';const style=getComputedStyle(button);menu.style.cssText=`position:fixed;z-index:25000;display:grid;gap:4px;padding:6px;border:1px solid ${style.borderColor};border-radius:${style.borderRadius};background:var(--bg-card,#fffaf2);box-shadow:0 5px 18px #0002;font-family:${style.fontFamily};font-size:${style.fontSize};min-width:150px`;
    for(const [format,label] of [['xlsx','Excel (.xlsx)'],['csv','CSV (.csv)']]){const option=document.createElement('button');option.type='button';option.role='menuitem';option.className=button.className;option.textContent=label;option.style.cssText='text-align:left;white-space:nowrap;margin:0';option.onclick=async()=>{close();if(root.mockExportGuard&&!root.mockExportGuard(button))return;if(prepare)return prepare(format);const context=root.mockExportContext?.(button)||'';notify(`${format==='xlsx'?'Excel':'CSV'} export prepared for demo.${context?' '+context:''}`);};menu.append(option);}
    document.body.append(menu);const r=button.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(r.left,innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.min(r.bottom+5,innerHeight-menu.offsetHeight-8)+'px';menu.firstChild.focus();}
  document.addEventListener('click',e=>{if(menu?.contains(e.target))return;const b=e.target.closest('button,a,[role=button]');if(!b||!/^Export\b/i.test(b.textContent.trim())){close();return;}if(b.disabled||b.getAttribute('aria-disabled')==='true'){close();return;} e.preventDefault();e.stopImmediatePropagation();if(root.mockExportGuard&&!root.mockExportGuard(b))return;open(b,root.mockExportPrepare?format=>root.mockExportPrepare(b,format):null);},true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu){const b=trigger;close();b?.focus();}});root.addEventListener('resize',close);root.addEventListener('scroll',close,true);
  root.MockExport={open,close,notify};
})(window);
