const assert=require('node:assert/strict');
const vm=require('node:vm');const fs=require('node:fs');
const data=new Map();const localStorage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v))};
const ctx={localStorage,console,Date,Map,Set,Object,JSON,Number,String};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['mock-workflows.js','ba-workflows.js'])vm.runInContext(fs.readFileSync(f,'utf8'),ctx);
const W=ctx.YuushiWorkflow,B=ctx.YuushiBA;
const transactions=localStorage.getItem(W.keys.transactions);
const property={id:'PROP-QA',agencyId:'AG-QA'};W.write('qa.properties',[property]);
const q={customerId:'CLIENT-QA',agencyId:'AG-QA',propertyId:'PROP-QA'};
const first=B.openInquiry(q);assert.equal(first.created,true);assert.equal(first.record.assigneeId,null);assert.equal(first.record.assignedStaffId,null);
assert.equal(B.openInquiry(q).record.id,first.record.id);assert.equal(W.read(W.keys.enquiries).length,1);
W.assign(first.record,'Agent Individual',W.AGENCY_SUB_ACCOUNTS[0],'Assigned by Agency','QA Admin');W.upsert(W.keys.enquiries,first.record);
assert.equal(B.openInquiry(q).record.assignedStaffId,'AGT-001');assert.equal(W.read(W.keys.enquiries).length,1);
W.write(W.keys.leadRecords,[{id:first.record.id,status:'Viewing',propertyId:q.propertyId},{id:'closed',status:'Sold',assignedStaffId:'AGT-001',soldPrice:123}]);
assert.equal(B.setStaffStatus({id:'AGT-001',name:'Chris Sales'},'Suspended','QA Admin'),1);
const lead=W.read(W.keys.leadRecords)[0];assert.equal(lead.status,'Closed Lost');assert.equal(lead.previousAssignedStaffId,'AGT-001');assert.equal(lead.assignmentHistory.at(-1).actor,'QA Admin');
assert.equal(W.read(W.keys.leadRecords)[1].status,'Sold');assert.equal(B.refreshStaff().some(s=>s.id==='AGT-001'),false);
assert.throws(()=>W.assign({},'Agent Individual',{id:'AGT-001',name:'Chris Sales'},'','QA'),/suspended/);
assert.equal(B.openInquiry(q).record.id,first.record.id);assert.equal(W.read(W.keys.enquiries).length,1);
assert.equal(W.read('qa.properties')[0].id,'PROP-QA');assert.equal(localStorage.getItem(W.keys.transactions),transactions);
assert.equal(W.read(B.staffKey).find(s=>s.staffId==='AGT-001').history.at(-1).actor,'QA Admin');
B.setStaffStatus({id:'AGT-001',name:'Chris Sales'},'Active','QA Admin');assert.equal(W.read(W.keys.leadRecords)[0].status,'Closed Lost');
assert.notEqual(B.openInquiry({...q,propertyId:'PROP-OTHER'}).record.id,first.record.id);
console.log('PASS: inquiry reuse/unassigned routing, suspension eligibility/history/Closed Lost, historical sale/property/conversation and transaction workflow preservation.');
