/* Source mapping and fixture limitations: REVIEW-MAPPING.md. */
const NOW='2026-09-15', CLOCK='2026-09-15T00:00:00Z';
const categories=['Law','Tax','Repair','Construction','Mortgage Provider','Mortgage Broker','Property Manager','Insurance'];
const products=['Homepage Carousel — New Development','Homepage Carousel — Featured Properties','Static Banner','Sponsored Search','In-Article Banner','Property Detail Banner','City/Area Detail Banner','Supportal Search Banner'];
const seed={plans:[],features:[{id:'listings',name:'Listings',accounts:['Agency','Supportal'],type:'quota',unit:'listings'},{id:'requests',name:'Lead / Service Request quota',accounts:['Agency','Supportal'],type:'quota',unit:'requests/month'},{id:'crm',name:'CRM Enhancement',accounts:['Agency','Supportal'],type:'boolean',unit:''},{id:'history',name:'Message History',accounts:['Client'],type:'quota',unit:'months'},{id:'compare',name:'Comparison Tool',accounts:['Client'],type:'quota',unit:'properties'},{id:'block',name:'Block agents / properties',accounts:['Client'],type:'boolean',unit:''}],addons:[],slots:[],bookings:[],transactions:[],audit:[],settings:{coefficient:1.2,reminder:7,duplicate:60,Agency:1.2,Supportal:1.1,tierA:45000,tierB:30000,tierC:15000,discount1:0,discount2:2,discount3:5,hometown:10,visible:false,riskDays:7,staleDays:7,warningDelivery:90,criticalDelivery:70,severeDelivery:50},wards:[{name:'Shibuya',tier:'A'},{name:'Setagaya',tier:'B'},{name:'Nerima',tier:'B'},{name:'Ota',tier:'C'},{name:'Musashino',tier:'B'}],rules:{Subscription:{increase:10,annual:25,cooldown:90,decrease:15,strongConversion:15,weakConversion:3,renewal:90,churn:15,minCycles:2,minViews:20,minPurchases:5},Cart:{increase:15,annual:40,cooldown:30,decrease:20,strongCart:20,repeat:25,abandonment:60,minCycles:1,minViews:20,minPurchases:3},Advertising:{increase:15,annual:40,cooldown:60,decrease:15,highOccupancy:85,lowOccupancy:30,waitlist:2,minCycles:2,minViews:1000,minPurchases:2}},recommendations:[]};
[['Free','Client',0,0,''],['Customer Plus','Client',2500,10,''],['Free','Agency',0,0,''],['Silver','Agency',12000,20,''],['Gold','Agency',28000,30,''],['Platinum','Agency',60000,40,''],['Gold — Law','Supportal',22000,30,'Law'],['Gold — Repair','Supportal',25000,30,'Repair'],['Legacy Bronze','Agency',8000,10,'']].forEach((x,i)=>seed.plans.push({id:'P'+i,name:x[0],account:x[1],price:x[2],tier:x[3],category:x[4],cycle:'Monthly',status:i===8?'Retired':'Active',score:x[3]===40?500:x[3]===30?100:x[3]===20?50:10,wards:x[3]===30?5:1,discount6:10,discount12:20,disclaimer:x[3]===40?'Unlimited requests; covered wards are limited. Contact frequency varies with ratings.':'',features:Object.fromEntries(seed.features.filter(f=>f.accounts.includes(x[1])).map(f=>[f.id,{state:'Included',limit:f.type==='boolean'?'None':x[3]===40||f.id==='history'&&i===1?'Unlimited':'Fixed',value:f.type==='boolean'?0:f.id==='requests'?(x[3]===30?5:x[3]===20?1:0):f.id==='compare'?5:f.id==='history'?3:20}])),subscribers:x[2]?i===4?182:i===1?412:36:0}));
[['Additional Coverage Area',0,['Agency','Supportal'],'Ward'],['Additional Service Category',8000,['Supportal'],'Category'],['Additional Listing Slots',5000,['Agency','Supportal'],'Listings'],['Profile Enhancement — Standard',3000,['Agency','Supportal'],'Account'],['Profile Enhancement — Premium',7000,['Agency','Supportal'],'Account'],['CRM Enhancement — Standard',4000,['Agency','Supportal'],'Account'],['CRM Enhancement — Premium',9000,['Agency','Supportal'],'Account'],['Additional User Seat',1500,['Agency','Supportal'],'Seats']].forEach((x,i)=>seed.addons.push({id:'A'+i,name:x[0],accounts:x[2],unit:x[3],variants:[{quantity:i===2?5:1,months:1,price:x[1]}],disclaimer:'',volume:[1,.95,.9]}));
function slot(product,scope,rate,mode='Monthly',available=1){seed.slots.push({id:'S'+seed.slots.length,product,scope,rate,mode,capacity:8,available,ranges:[],waitlist:[]});}
[0,1].forEach(p=>[1,2,3,4,5].forEach(n=>slot(p,'Position '+n,60000-n*3000)));
['Area Guide','Mortgage Calculator','Agency Search'].forEach((s,i)=>slot(2,s,[28000,26000,30000][i]));
['Nishi-Shinjuku · Area','Shinjuku Station · Station','Shibuya · Area'].forEach(l=>['Apartment','Detached House'].forEach(t=>[1,2].forEach(r=>slot(3,`${l} / ${t} / Rank ${r}`,r===1?1800:1450,'CPM'))));
['Buying Guide','Market Insight','Renovation'].forEach((c,i)=>slot(4,c,1200,'CPM',i===2?0:12));
['Nishi-Shinjuku · Area','Shibuya · Area','Shinjuku Station · Station'].forEach(l=>['Apartment','Detached House'].forEach(t=>slot(5,`${l} / ${t}`,1100,'CPM',l.includes('Station')&&t==='Detached House'?0:24)));
['City / Shinjuku City','City / Shibuya City','Area / Nishi-Shinjuku','Area / Shibuya'].forEach(s=>slot(6,s,31000));slot(7,'Supportal Search',25000);
[['AD-10245','Kanto Realty',13,106900,'2026-09-09','2026-09-13','2026-12-13','Nishi-Shinjuku Residence','Bright apartments near Shinjuku Station. Arrange a viewing today.','property'],['AD-10248','Sunrise Realty',12,58800,'2026-09-11','2026-09-20','2026-11-20','Sunrise Realty','Find your next home with local property specialists.','agency'],['AD-10251','Metro Homes',25,42000,'2026-09-14','2026-09-25','2026-10-25','Metro Homes','A clearer path to buying your first home.','agency'],['AD-10253','Tokyo Law Partners',38,25000,'2026-09-15','2026-09-28','2026-10-28','Tokyo Law Partners','Property contracts explained by experienced legal advisers.','supportal']].forEach((x,i)=>{const s=seed.slots[x[2]];seed.bookings.push({id:x[0],account:x[1],slot:s.id,price:x[3],submitted:x[4],start:x[5],end:x[6],title:x[7],copy:x[8],destination:x[9],status:'Pending Review',creative:'creative-'+i+'.svg',deadline:new Date(Date.parse(x[4])+7*864e5).toISOString().slice(0,10)});});
seed.slots[12].capacity=2;
seed.slots[12].waitlist=[{account:'Green Estate',date:'2026-09-20',requested:'2026-09-10'}];
seed.bookings.push({id:'AD-10231',account:'Urban Estate',slot:'S12',price:30000,submitted:'2026-08-25',start:'2026-09-01',end:'2026-10-01',title:'Urban Estate',copy:'Homes for city living.',destination:'agency',status:'Active',creative:'creative-1.svg',deadline:'2026-09-01',delivered:0,estimated:20000});
seed.plans.filter(p=>p.price&&p.status==='Active').forEach((p,i)=>seed.transactions.push({id:'TX-P'+i,engine:'Subscription',account:i===0?'Aiko Tanaka':'Kanto Realty',date:'2026-09-10',event:'Charge',amount:p.price,object:p.id,status:'Succeeded',reason:''}));
seed.addons.filter(a=>a.id!=='A0').forEach((a,i)=>seed.transactions.push({id:'TX-A'+i,engine:'Cart',account:'Sunrise Realty',date:'2026-09-12',event:'Charge',amount:a.variants[0].price,object:a.id,status:'Succeeded',reason:''}));
seed.transactions.push({id:'TX-AD31',engine:'Advertising',account:'Urban Estate',date:'2026-09-01',event:'Capture',amount:30000,object:'AD-10231',status:'Succeeded',reason:''},{id:'TX-F1',engine:'Subscription',account:'Kanto Realty',date:'2026-09-14',event:'Charge',amount:28000,object:'P4',status:'Failed',reason:'Card declined'},{id:'TX-F2',engine:'Cart',account:'Green Estate',date:'2026-09-07',event:'Charge',amount:5000,object:'A2',status:'Failed',reason:'Insufficient funds'});
seed.bookings.filter(b=>b.status==='Pending Review').forEach(b=>seed.transactions.push({id:'H-'+b.id,engine:'Advertising',account:b.account,date:b.submitted,event:'Authorization',amount:b.price,object:b.id,status:'Pending',reason:''}));
[['Subscription','P4',30800],['Cart','A2',5500],['Advertising','S12',33000],['Advertising','S7',54450]].forEach((x,i)=>seed.recommendations.push({id:'R'+i,engine:x[0],object:x[1],price:x[2],status:'Pending Review',last:'2026-05-01',confidence:i===2?'Medium':'High',annualChange:0}));
seed.audit.push({id:'LOG-1',date:'2026-09-14',actor:'Thu',action:'Rejected booking',engine:'Advertising',object:'AD-10238',before:{status:'Pending Review'},after:{status:'Rejected'},reason:'Creative quality'});
Object.assign(seed.rules.Subscription,{upgradeInflow:10,noPurchasesDays:45,cancellation:20,cancellationWindow:60,strongMonths:3,weakMonths:2,renewalCycles:2});
Object.assign(seed.rules.Cart,{weakCart:5,noPurchasesDays:60,observationMonths:2,repeatWindow:90,tierHigh:2,tierLow:.7});
Object.assign(seed.rules.Advertising,{concurrent:3,noPurchasesDays:45,highMonths:3,lowMonths:2,minPeers:5,trafficWeight:40,demandWeight:30,qualityWeight:30,peerWeight:70,historicalWeight:30});
let db;try{db=JSON.parse(localStorage.getItem('yuushi-cms-v1'))||structuredClone(seed)}catch{db=structuredClone(seed)}
