'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), money=n=>'¥'+Number(n).toLocaleString('en-US'), clone=v=>structuredClone(v), screen=+document.body.dataset.screen;
const files=['01-plans-features','02-appraisal-request-settings','03-addon-cart-management','04-ad-pricing-management','05-booking-approvals','06-pricing-recommendations','07-revenue','08-dashboard','09-audit-log','10-operations-finance-control'];
let view={},pending,dirty=false,focusBefore;
const btn=(text,fn,kind='secondary')=>`<button type="button" class="btn ${kind}" onclick="${fn}">${text}</button>`;
const badge=s=>`<span class="pill ${/Failed|Rejected|Critical/.test(s)?'red':/Pending|Draft|Warning/.test(s)?'amber':'green'}">${esc(s)}</span>`;
function table(head,rows){return `<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${head.length}" class="muted">No matching records. Adjust your filters.</td></tr>`}</tbody></table></div>`;}
function field(name,label,value,type='text',extra=''){return `<label class="field"><span class="label">${label}</span><input class="input" name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(name,label,values,value,extra=''){return `<label class="field"><span class="label">${label}</span><select class="select" name="${name}" ${extra}>${values.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('')}</select></label>`;}
function checks(name,values,selected){return `<fieldset class="field"><legend class="label">Applicable account types</legend>${values.map(v=>`<label><input type="checkbox" name="${name}" value="${v}" ${selected.includes(v)?'checked':''}> ${v} </label>`).join('')}</fieldset>`;}
const textArea=(name,label,v)=>`<label class="field"><span class="label">${label}</span><textarea class="textarea" name="${name}">${esc(v)}</textarea></label>`;
function form(body,save='submitEdit(event)',label='Review changes'){return `<form id="editForm" onsubmit="${save}" oninput="markDirty()"><div class="drawer-body">${body}<p id="formError" class="error" role="alert"></p></div><footer class="drawer-foot"><span id="dirty" class="dirty"></span>${btn('Cancel','closeEditor()')}<button class="btn primary">${label}</button></footer></form>`;}
function drawer(title,body){focusBefore=document.activeElement;dirty=false;$('#editor').innerHTML=`<header class="drawer-head"><strong>${esc(title)}</strong>${btn('Close','closeEditor()','ghost')}</header>${body}`;$('#editor').classList.add('open');$('#overlay').classList.add('show');$('#editor').querySelector('input,select,button')?.focus();}
function closeEditor(force=false){if(dirty&&!force){review('Discard unsaved changes?','<p>Your saved record will remain unchanged.</p>',()=>closeEditor(true),'Discard changes');return}$('#editor').classList.remove('open');$('#overlay').classList.remove('show');dirty=false;focusBefore?.focus();}
function markDirty(){dirty=true;if($('#dirty'))$('#dirty').textContent='Unsaved changes';}
function review(title,body,action,label='Confirm',typed=false){pending=action;$('#confirm').innerHTML=`<h2>${esc(title)}</h2>${body}<form onsubmit="event.preventDefault();confirmAction()">${typed?field('confirmWord','Type CONFIRM to reveal performance figures','','text','required pattern="CONFIRM"'):''}<p id="confirmError" class="error" role="alert"></p><div class="modal-actions">${btn('Back',"document.querySelector('#confirm').close()") }<button class="btn primary">${label}</button></div></form>`;$('#confirm').showModal();}
function confirmAction(){if(!$('#confirm form')||!$('#confirm form').reportValidity())return;try{pending();$('#confirm').close()}catch(e){$('#confirmError').textContent=e.message}}
function persist(){localStorage.setItem('yuushi-cms-v1',JSON.stringify(db));}
function log(action,engine,object,before,after,reason=''){db.audit.unshift({id:'LOG-'+Date.now(),date:NOW,actor:'Thu',action,engine,object,before:clone(before),after:clone(after),reason});}
function commit(action,engine,object,before,after,apply){apply();log(action,engine,object,before,after);persist();closeEditor(true);render();}
function displayValue(v,key='') {if(v==null)return '—';if(Array.isArray(v))return v.map(x=>displayValue(x)).join('<br>');if(typeof v==='object')return Object.entries(v).map(([k,x])=>`<div><strong>${esc(db.features.find(f=>f.id===k)?.name||labels[k]||k)}</strong>: ${displayValue(x,k)}</div>`).join('');return esc(v);}
const labels={name:'Name',account:'Account type',category:'Service category',cycle:'Billing cycle',price:'Price · JPY',tier:'Tier order',status:'Status',score:'Ranking base score',wards:'Included wards',discount6:'6-month discount · %',discount12:'12-month discount · %',features:'Feature assignments',state:'Assignment',limit:'Quota type',value:'Quota',accounts:'Applicable accounts',type:'Value type',unit:'Unit',variants:'Purchase options',quantity:'Quantity',months:'Months',disclaimer:'Buyer disclosure',volume:'Volume multipliers',rate:'Rate · JPY',capacity:'Concurrent capacity',start:'From',end:'Through',mode:'Pricing model',cutoff:'Mode effective date',visible:'Detailed performance visible',ranges:'Price calendar',effective:'Effective date'};
function diff(a,b){return table(['Configuration','Current','Proposed'],Object.keys(b).filter(k=>JSON.stringify(a[k])!==JSON.stringify(b[k])).map(k=>[esc(labels[k]||ruleLabels?.[k]||k),displayValue(a[k],k),displayValue(b[k],k)]));}

function validForm(e){e.preventDefault();return new FormData(e.target)}
function fail(msg){$('#formError').textContent=msg;return false}
function tabs(items){return `<div class="tabs">${items.map(([k,n])=>btn(n,`view.tab='${k}';render()`,(screen===6?view.engine:view.tab)===k?'primary':'ghost')).join('')}</div>`;}
function filters(items){return `<div class="filters">${items.join('')}</div>`;}
function filterInput(k,label='Search'){return field(k,label,view[k]||'','search',`oninput="view.${k}=this.value;renderRows()"`)}
function filterSelect(k,label,values){return select(k,label,['All',...values],view[k]||'All',`onchange="view.${k}=this.value;renderRows()"`)}
function matches(row){return (!view.q||JSON.stringify(row).toLowerCase().includes(view.q.toLowerCase()))}
function link(n,id,text){return `<a href="${files[n-1]}.html${id?'?object='+encodeURIComponent(id):''}">${esc(text)}</a>`;}
function details(title,data){drawer(title,`<div class="drawer-body">${table(['Field','Value'],Object.entries(data).map(([k,v])=>[esc(k),esc(typeof v==='object'?JSON.stringify(v):v)]))}</div>`)}
function planScope(p){return p.account+(p.category?' · '+p.category:'')}
function impact(p){return `<h3>${p.subscribers} affected subscribers</h3><p>Current paid terms remain until each cycle ends. Renewal requires acceptance of the new terms. Without acceptance, the account returns to its baseline plan at cycle end.</p>${p.subscribers?`<details><summary>Subscriber cohort</summary>${table(['Cohort','Count','Cycle ends'],[[esc(planScope(p)+' · '+p.name),p.subscribers,'16 Sep – 15 Oct 2026']])}<p class="small">Aggregate mock cohort; individual subscriber identities are not supplied.</p></details>`:''}`;}
function plans(){view.tab??='plans';return tabs([['plans','Plans & Features'],['registry','Feature Registry'],['ranking','Search Ranking']])+(view.tab==='ranking'?`<section class="card"><h2>Global ranking settings</h2><p>Plan base scores are edited with each plan.</p>${btn('Configure global coefficient and renewal reminder',"settingsEditor('subscription')")}${table(['Plan','Scope','Base score',''],db.plans.filter(p=>p.account!=='Client').map(p=>[esc(p.name),esc(planScope(p)),p.score,btn('Edit plan',`editPlan('${p.id}')`)]))}</section>`:view.tab==='registry'?`<section class="card"><div class="between"><h2>Feature Registry</h2>${btn('New feature',"editFeature()",'primary')}</div><div id="rows"></div></section>`:`<section class="card"><div class="between"><h2>Plan catalog</h2>${btn('New plan','editPlan()','primary')}</div>${filters([filterInput('q'),filterSelect('account','Account type',['Client','Agency','Supportal']),filterSelect('status','Status',['Draft','Active','Retired'])])}<div id="rows"></div></section>`);}
function planRows(){if(view.tab==='registry')return table(['Feature','Accounts','Value type','Unit',''],db.features.map(f=>[esc(f.name),esc(f.accounts.join(', ')),f.type,esc(f.unit),btn('Edit',`editFeature('${f.id}')`)]));return table(['Plan','Scope','Billing','Price','Tier','Status','Subscribers',''],db.plans.filter(p=>matches(p)&&(!view.account||view.account==='All'||p.account===view.account)&&(!view.status||view.status==='All'||p.status===view.status)).map(p=>[esc(p.name),esc(planScope(p)),esc(p.cycle),money(p.price),p.tier,badge(p.status)+(p.scheduledPrice?'<br><small>'+money(p.scheduledPrice.price)+' from '+p.scheduledPrice.date+'</small>':''),p.subscribers,btn('Edit',`editPlan('${p.id}')`)]));}
let editing;
function editPlan(id){const p=clone(db.plans.find(p=>p.id===id)||{id:'P'+Date.now(),name:'',account:'Agency',category:'',cycle:'Monthly',price:0,tier:1,status:'Draft',score:10,wards:0,features:{},discount6:0,discount12:0,disclaimer:'',subscribers:0});editing={kind:'plan',old:p,isNew:!id};drawer(id?'Edit '+p.name:'Create plan',form(`<div class="grid2">${field('name','Plan name',p.name,'text','required')}${select('account','Account type',['Client','Agency','Supportal'],p.account,'onchange="changePlanAudience(this.value)"')}${select('category','Supportal category',['',...categories],p.category,'id="planCategory"')}${select('cycle','Billing cycle',['Monthly','Yearly'],p.cycle)}${field('price','Recurring price · JPY',p.price,'number','min="0" step="1" required')}${field('tier','Tier order',p.tier,'number','min="0" step="1" required')}${select('status','Status',['Draft','Active','Retired'],p.status)}<div id="scoreField">${field('score','Ranking base score',p.score,'number','min="0" step="0.1" required')}</div></div><h3>Feature assignments</h3><div id="featureFields"></div><div id="coverageField">${field('wards','Included ward coverage',p.wards,'number','min="0" step="1" required')}</div><h3>Commitment discounts</h3><div class="grid2">${field('discount6','6 months · %',p.discount6,'number','min="0" max="100" step="0.1" required')}${field('discount12','12 months · %',p.discount12,'number','min="0" max="100" step="0.1" required')}</div>${textArea('disclaimer','Customer-facing disclosure',p.disclaimer)}${id&&p.status!=='Retired'?btn('Retire plan',`retirePlan('${id}')`,'danger'):''}`));changePlanAudience(p.account);}
function changePlanAudience(account){$('#planCategory').disabled=account!=='Supportal';$('#planCategory').required=account==='Supportal';$('#scoreField').hidden=account==='Client';$('#coverageField').hidden=account==='Client';const p=editing.old;$('#featureFields').innerHTML=table(['Feature','Assignment','Quota','Value'],db.features.filter(f=>f.accounts.includes(account)).map(f=>{const a=p.features[f.id]||{state:'Not available',limit:'None',value:0};return [esc(f.name),select('state_'+f.id,'State',['Not available','Included','Paid add-on'],a.state),f.type==='quota'?select('limit_'+f.id,esc(f.unit),['Fixed','Unlimited','None'],a.limit):'—',f.type==='quota'?field('value_'+f.id,'Quota',a.value,'number','min="0" step="1" required'):'—']}));}
function retirePlan(id){const p=db.plans.find(p=>p.id===id);review('Retire '+p.name,`<p>No new subscriptions or renewals. Existing subscribers keep access until cycle end, then choose a replacement or return to baseline. No automatic migration.</p>${impact(p)}`,()=>commit('Retired plan','Subscription',id,p,{...p,status:'Retired'},()=>p.status='Retired'),'Retire plan');}
function editFeature(id){const f=clone(db.features.find(f=>f.id===id)||{id:'F'+Date.now(),name:'',accounts:['Agency'],type:'boolean',unit:''});editing={kind:'feature',old:f,isNew:!id};drawer('Feature Registry · '+(f.name||'New feature'),form(`${field('name','Display name',f.name,'text','required')}${checks('accounts',['Client','Agency','Supportal'],f.accounts)}${select('type','Value type',['boolean','quota'],f.type)}${field('unit','Quota unit (required for quota)',f.unit)}${id?btn('Remove feature',`removeFeature('${id}')`,'danger'):''}`));}
function removeFeature(id){const f=db.features.find(f=>f.id===id),affected=db.plans.filter(p=>p.features[id]);review('Remove feature '+f.name,`<p>${affected.length} plans use this feature. Their assignments will be removed.</p>${affected.map(impact).join('')}`,()=>commit('Removed feature','Subscription',id,f,{},()=>{db.features=db.features.filter(f=>f.id!==id);affected.forEach(p=>delete p.features[id])}),'Remove feature');}
function submitEdit(e){const d=validForm(e),old=editing.old;
 if(editing.kind==='plan'){const p={...old,...Object.fromEntries(d),features:{}};['price','tier','score','wards','discount6','discount12'].forEach(k=>p[k]=Number(p[k]));if(p.account!=='Supportal')p.category='';if(p.account==='Supportal'&&!p.category)return fail('Select a Supportal category.');db.features.filter(f=>f.accounts.includes(p.account)).forEach(f=>p.features[f.id]={state:d.get('state_'+f.id),limit:d.get('state_'+f.id)==='Not available'?'None':d.get('limit_'+f.id)||'None',value:d.get('state_'+f.id)==='Not available'||d.get('limit_'+f.id)!=='Fixed'?0:+d.get('value_'+f.id)||0});Object.keys(p).filter(k=>/^(state|limit|value)_/.test(k)).forEach(k=>delete p[k]);if(old.status==='Active'&&p.status==='Draft')return fail('An active plan cannot return to draft. Retire it to stop new purchases.');if(p.status==='Retired'&&editing.isNew)return fail('Create a draft or active plan first.');const higher=db.plans.find(q=>q.id!==p.id&&q.account===p.account&&q.category===p.category&&q.tier>p.tier&&q.score<p.score);review('Publish plan changes',diff(old,p)+(p.subscribers?impact(p):'<p>These terms will be offered to new subscribers.</p>')+(p.status==='Retired'?'<p>This plan will stop accepting purchases and renewals. No automatic migration.</p>':'')+(higher?`<p class="alert warn">${esc(p.name)} has a higher ranking score than higher-tier ${esc(higher.name)}. Confirm to proceed.</p>`:''),()=>commit('Changed plan','Subscription',p.id,old,p,()=>{const i=db.plans.findIndex(x=>x.id===p.id);if(i<0)db.plans.push(p);else db.plans[i]=p}),'Publish');
 }else if(editing.kind==='feature'){const f={...old,name:d.get('name').trim(),accounts:d.getAll('accounts'),type:d.get('type'),unit:d.get('type')==='quota'?d.get('unit').trim():''};if(!f.accounts.length||f.type==='quota'&&!f.unit)return fail('Select an account type and specify the quota unit.');const affected=db.plans.filter(p=>p.features[f.id]);review('Save feature',diff(old,f)+affected.map(impact).join(''),()=>commit('Changed feature','Subscription',f.id,old,f,()=>{const i=db.features.findIndex(x=>x.id===f.id);if(i<0)db.features.push(f);else db.features[i]=f;affected.forEach(p=>{if(!f.accounts.includes(p.account))delete p.features[f.id];else if(f.type==='boolean')p.features[f.id]={state:p.features[f.id].state,limit:'None',value:0}})}),'Publish feature');
 }else if(editing.kind==='settings'){const next=Object.fromEntries([...d].map(([k,v])=>[k,+v]));if(next.warningDelivery!==undefined&&!(next.warningDelivery>next.criticalDelivery&&next.criticalDelivery>next.severeDelivery))return fail('Delivery thresholds must descend: warning > critical > severe.');review('Save configuration',diff(db.settings,next),()=>commit('Changed settings',editing.engine,'Global',db.settings,{...db.settings,...next},()=>Object.assign(db.settings,next)));
 }else if(editing.kind==='addon'){saveAddon(d)}else if(editing.kind==='slot'){saveSlot(d)}else if(editing.kind==='rules'){const next=Object.fromEntries([...d].map(([k,v])=>[k,+v]));if(editing.engine==='Advertising'&&(next.trafficWeight+next.demandWeight+next.qualityWeight!==100||next.peerWeight+next.historicalWeight!==100))return fail('Score weights must total 100%; peer and historical weights must also total 100%.');if(editing.engine==='Cart'&&next.tierLow>=next.tierHigh)return fail('Tier C threshold must be below the Tier A threshold.');review('Save '+editing.engine+' pricing rules',diff(old,next),()=>commit('Changed pricing rules',editing.engine,'Guardrails',old,next,()=>db.rules[editing.engine]=next));}}
function settingsEditor(kind){let fields,engine;if(kind==='subscription'){fields=[['coefficient','Global rating coefficient',.1],['reminder','Renewal reminder · days before cycle end',1]];engine='Subscription'}else if(kind==='request'){fields=[['duplicate','Duplicate request window · days',1],['Agency','Agency rating weight',.1],['Supportal','Supportal rating weight',.1]];engine='Subscription'}else if(kind==='tiers'){fields=['A','B','C'].map(t=>['tier'+t,'Tier '+t+' · monthly JPY',1]);engine='Cart'}else if(kind==='ads'){fields=[['discount1','First month discount · %',.1],['discount2','Second month discount · %',.1],['discount3','Third month discount · %',.1],['hometown','Exact-location discount · %',.1]];engine='Advertising'}else{fields=[['riskDays','Renewal risk · days before cycle end',1],['warningDelivery','Delivery warning below · %',1],['criticalDelivery','Critical delivery below · %',1],['severeDelivery','Severe delivery at halfway · %',1]];engine='Advertising'}editing={kind:'settings',old:clone(db.settings),engine};drawer('Configure '+kind,form(fields.map(([k,l,step])=>field(k,l,db.settings[k],'number',`required min="0" step="${step}" ${l.includes('%')?'max="100"':''}`)).join('')));}
function requests(){view.tab??='quota';return tabs([['quota','Quota & Coverage'],['tiers','Ward Tiers']])+(view.tab==='tiers'?`<section class="card"><h2>Ward tiers</h2>${filterInput('q','Search wards')}<div id="rows"></div><h3>Shared monthly coverage prices</h3>${table(['Tier','Monthly price'],['A','B','C'].map(t=>[t,money(db.settings['tier'+t])]))}${btn('Edit tier prices',"settingsEditor('tiers')")}</section>`:`<section class="card"><h2>Plan quota and included coverage</h2>${filters([filterSelect('account','Account type',['Agency','Supportal']),filterSelect('category','Service category',categories)])}<div id="rows"></div><p class="small">Edit each plan to review quota changes and affected subscribers together.</p></section><section class="card"><h2>Request distribution settings</h2>${table(['Setting','Current value'],[['Duplicate request window',db.settings.duplicate+' days'],['Agency rating weight',db.settings.Agency],['Supportal rating weight',db.settings.Supportal]])}${btn('Configure',"settingsEditor('request')")}</section>`);}
function requestRows(){if(view.tab==='tiers')return table(['Ward','Tier'],db.wards.filter(matches).map(w=>[esc(w.name),`<select class="select" aria-label="${esc(w.name)} tier" onchange="wardChange('${w.name}',this.value);this.value='${w.tier}'">${['A','B','C'].map(t=>`<option ${t===w.tier?'selected':''}>${t}</option>`).join('')}</select>`]));return table(['Plan','Account / category','Monthly quota','Included wards',''],db.plans.filter(p=>p.account!=='Client'&&p.status!=='Retired'&&(!view.account||view.account==='All'||p.account===view.account)&&(!view.category||view.category==='All'||p.category===view.category)).map(p=>[esc(p.name),esc(planScope(p)),p.features.requests?.limit==='Unlimited'?'Unlimited':p.features.requests?.value||'None',p.wards,btn('Edit plan',`editPlan('${p.id}')`)]));}
function wardChange(name,tier){const w=db.wards.find(w=>w.name===name);review('Change '+name+' tier',diff(w,{...w,tier})+`<p>New coverage purchases use ${money(db.settings['tier'+tier])}/month. Existing coverage keeps its paid terms until renewal.</p>`,()=>commit('Changed ward tier','Cart',name,w,{...w,tier},()=>w.tier=tier));}
function addons(){return `<section class="card"><h2>Existing add-on catalog</h2>${filterInput('q')}<div id="rows"></div></section>`;}
function addonRows(){return table(['Add-on','Accounts','Unit','Variants / current price',''],db.addons.filter(matches).map(a=>[esc(a.name),esc(a.accounts.join(', ')),esc(a.unit),a.id==='A0'?link(2,'tiers','Ward tier prices'):a.variants.map(v=>`${v.quantity} × ${v.months} month(s) · ${money(v.price)}`).join('<br>')+(a.scheduledPrice?'<br><small>'+money(a.scheduledPrice.price)+' from '+a.scheduledPrice.date+'</small>':''),btn('Configure',`editAddon('${a.id}')`)]));}
function editAddon(id){const a=clone(db.addons.find(a=>a.id===id));editing={kind:'addon',old:a};drawer(a.name,form(`${checks('accounts',id==='A1'?['Supportal']:['Agency','Supportal'],a.accounts)}<p>Purchase unit: ${esc(a.unit)}</p>${a.id==='A0'?`<p>${link(2,'tiers','Configure shared Ward Tier prices')} · Gold / Platinum coverage purchases</p>`:''}<h3>Purchasable variants</h3><div id="variants"></div>${btn('Add duration / bundle option','addVariant()')}<h3>Volume pricing</h3>${a.id==='A0'?'<p>Coverage uses the shared tier prices.</p>':`<div class="grid3">${a.volume.map((v,i)=>field('volume'+i,['1–4 units · multiplier','5–9 units · multiplier','10+ units · multiplier'][i],v,'number','min="0" max="1" step="0.01" required')).join('')}</div>`}${textArea('disclaimer','Buyer-facing disclosure',a.disclaimer)}`));variantRows();}
function variantRows(){const a=editing.old;$('#variants').innerHTML=table(['Quantity / bundle','Duration · months','Price · JPY',''],a.variants.map((v,i)=>[field('quantity'+i,'Quantity',v.quantity,'number','required min="1" step="1"'),field('months'+i,'Months',v.months,'number','required min="1" step="1"'),a.id==='A0'?'Ward tier × duration':field('price'+i,'JPY',v.price,'number','required min="0" step="1"'),a.variants.length>1?btn('Remove option',`removeVariant(${i})`):'']));}
function collectVariants(){const d=new FormData($('#editForm'));editing.old.variants=editing.old.variants.map((v,i)=>({quantity:+d.get('quantity'+i),months:+d.get('months'+i),price:+d.get('price'+i)}));}
function addVariant(){collectVariants();editing.old.variants.push({quantity:1,months:2,price:0});variantRows();markDirty()}
function removeVariant(i){collectVariants();editing.old.variants.splice(i,1);variantRows();markDirty()}
function saveAddon(d){const original=db.addons.find(a=>a.id===editing.old.id),a={...clone(editing.old),accounts:d.getAll('accounts'),disclaimer:d.get('disclaimer')};if(!a.accounts.length)return fail('Select an applicable account type.');a.variants=a.variants.map((v,i)=>({quantity:+d.get('quantity'+i),months:+d.get('months'+i),price:+d.get('price'+i)}));if(new Set(a.variants.map(v=>v.quantity+':'+v.months)).size!==a.variants.length)return fail('Each quantity and duration combination must be unique.');if(a.id!=='A0')a.volume=[0,1,2].map(i=>+d.get('volume'+i));review('Save '+a.name,diff(original,a)+'<p>New purchases use these options. Existing purchased durations and prices remain unchanged.</p>',()=>commit('Changed add-on','Cart',a.id,original,a,()=>db.addons[db.addons.findIndex(x=>x.id===a.id)]=a));}
function slotName(s){return products[s.product]+' · '+s.scope}
function inventory(){view.product??='0';const p=+view.product;return `<section class="card">${filters([select('product','Ad product',products,products[p],'onchange="view.product=products.indexOf(this.value);view.q=\'\';render()"'),filterInput('q','Search position, page or filter')])}<p>${p===7?'Supportal accounts':'Agency accounts'} · ${['Five fixed homepage positions','Five fixed homepage positions','Independent platform pages','Area or Station + Property Type + Rank','Published article categories','Area or Station + Property Type','City or Area + published page','One shared Supportal Search page'][p]}</p><div id="rows"></div>${[3,4,5,6].includes(p)?btn('Configure inventory slot','newSlot()'):''}</section><section class="card"><h2>Package pricing settings</h2>${table(['Package month','Discount'],[1,2,3].map(n=>[n,db.settings['discount'+n]+'%']))}${btn('Configure discounts',"settingsEditor('ads')")}</section>`;}
function inventoryRows(){return table(['Placement / filter','Rate','Capacity','Inventory',''],db.slots.filter(s=>s.product===+view.product&&matches(s)).map(s=>[esc(s.scope),money(s.rate)+(s.mode==='CPM'?' / 1,000 impressions':' / month'),s.capacity,s.available?badge('Available'):badge('Unavailable'),btn('Calendar / Configure',`editSlot('${s.id}')`)]));}
function newSlot(){const p=+view.product;drawer('Select platform inventory',`<form onsubmit="event.preventDefault();openSelectedSlot()"><div class="drawer-body">${[3,5].includes(p)?select('location','Location',['Nishi-Shinjuku · Area','Shibuya · Area','Shinjuku Station · Station'],'Nishi-Shinjuku · Area')+select('property','Property type',['Apartment','Detached House'],'Apartment'):''}${p===3?select('rank','Rank',['1','2'],'1'):''}${p===4?select('category','Published article category',['Buying Guide','Market Insight','Renovation'],'Buying Guide'):''}${p===6?select('page','Level / actual page',['City / Shinjuku City','City / Shibuya City','Area / Nishi-Shinjuku','Area / Shibuya'],'City / Shinjuku City'):''}<p class="small">Choose a platform entity to open its existing price calendar.</p></div><footer class="drawer-foot"><button class="btn primary">Open calendar</button></footer></form>`);}
function openSelectedSlot(){const d=new FormData($('#editor form')),p=+view.product,scope=p===3?`${d.get('location')} / ${d.get('property')} / Rank ${d.get('rank')}`:p===5?`${d.get('location')} / ${d.get('property')}`:p===4?d.get('category'):d.get('page');const s=db.slots.find(s=>s.product===p&&s.scope===scope);editSlot(s.id);}
function reserved(s,date){return db.bookings.filter(b=>b.slot===s.id&&['Pending Review','Approved','Active'].includes(b.status)&&b.start<=date&&b.end>date)}
function editSlot(id){const s=clone(db.slots.find(s=>s.id===id));editing={kind:'slot',old:s};drawer(slotName(s),form(`${!s.available?'<p class="alert danger">Unavailable: this category or filter has no published content. Pricing may be prepared; bookings remain unavailable.</p>':''}<div class="kv"><span>Current rate</span><strong>${money(s.rate)} · ${s.mode}</strong><span>Capacity</span><span>${s.capacity} concurrent accounts</span></div><h3>Price calendar & capacity</h3>${select('calendarMonth','Calendar month',['2026-09','2026-10','2026-11','2026-12'],'2026-09','onchange="calendarRows(this.value)"')}<div id="calendar"></div><p class="small">Reserved days include pending review. Grey days retain locked booking prices.</p><h3>Future price ranges</h3>${table(['From','Through','Rate','Capacity','Model',''],s.ranges.map((r,i)=>[r.start,r.end,money(r.rate),r.capacity,r.mode,btn('Edit range',`selectRange(${i})`)]))}<h3>Configure future range</h3><div class="grid2">${field('start','From','2026-10-02','date',`min="${NOW}" required`)}${field('end','Through','2026-10-31','date',`min="${NOW}" required`)}${select('mode','Pricing model',['Monthly','CPM'],s.mode)}${field('rate','Rate · JPY per month or 1,000 impressions',s.rate,'number','min="0" step="1" required')}${field('capacity','Concurrent account capacity',s.capacity,'number','min="1" step="1" required')}${field('cutoff','Mode change effective date (if changing model)','','date',`min="${NOW}"`)}</div><h3>Affected bookings</h3>${table(['Booking','Advertiser','Schedule','Locked price','Status'],db.bookings.filter(b=>b.slot===id).map(b=>[link(5,b.id,b.id),esc(b.account),b.start+' → '+b.end,money(b.price),badge(b.status)]))}<h3>Waitlist</h3>${table(['Priority','Account','Requested date','Joined'],s.waitlist.map((w,i)=>[i+1,esc(w.account),w.date,w.requested]))}`));calendarRows('2026-09');}
function calendarRows(month){const s=editing.old,days=new Date(+month.slice(0,4),+month.slice(5),0).getDate();$('#calendar').innerHTML=`<div class="calendar">${Array.from({length:days},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0'),books=reserved(s,date),r=s.ranges.find(r=>r.start<=date&&r.end>=date)||s;return `<button type="button" class="day ${books.length?'locked':''} ${books.length>=r.capacity?'full':''}" onclick="calendarDay('${date}')"><strong>${i+1}</strong><br>${books.length}/${r.capacity}<br><small>${money(r.rate)}</small></button>`}).join('')}</div>`;}
function calendarDay(date){const s=editing.old,books=reserved(s,date);review(date+' · '+s.scope,table(['Booking','Account','State','Locked price'],books.map(b=>[b.id,esc(b.account),badge(b.status),money(b.price)]))+table(['Waitlist account','Priority'],s.waitlist.filter(w=>w.date===date).map((w,i)=>[esc(w.account),i+1])),()=>{$('#editForm [name=start]').value=date;$('#editForm [name=end]').value=date;markDirty()},'Select date');}
function selectRange(i){editing.rangeIndex=i;const r=editing.old.ranges[i];Object.entries(r).forEach(([k,v])=>{const input=$('#editForm [name='+k+']');if(input)input.value=v});$('#editForm [name=start]').focus();markDirty();}
function saveSlot(d){const s=db.slots.find(s=>s.id===editing.old.id),r={start:d.get('start'),end:d.get('end'),mode:d.get('mode'),rate:+d.get('rate'),capacity:+d.get('capacity'),cutoff:d.get('cutoff')};if(r.start<NOW||r.end<r.start)return fail('Choose a future range with the end on or after the start.');const affected=db.bookings.filter(b=>b.slot===s.id&&['Pending Review','Approved','Active'].includes(b.status)&&b.start<=r.end&&b.end>r.start);if(affected.length)return fail('This range includes reserved dates. Select an unbooked range. Locked booking prices cannot be edited.');if(s.ranges.some((x,i)=>i!==editing.rangeIndex&&x.start<=r.end&&x.end>=r.start))return fail('This range overlaps an existing price range. Choose a separate range.');if(r.mode!==s.mode){if(!r.cutoff||r.cutoff!==r.start)return fail('Set the mode change date to the first day of this range.');if(db.bookings.some(b=>b.slot===s.id&&['Approved','Active'].includes(b.status)&&b.start<=r.cutoff&&b.end>r.cutoff))return fail('The mode change date overlaps an approved booking.');}review('Save future slot pricing',`<p>${esc(slotName(s))}</p>${diff({rate:s.rate,mode:s.mode,capacity:s.capacity},r)}<p>0 existing bookings affected. New purchases for this range use the new rate and capacity.</p>`,()=>commit('Changed slot calendar','Advertising',s.id,s,{...s,ranges:[...s.ranges,r]},()=>{if(editing.rangeIndex===undefined)s.ranges.push(r);else s.ranges[editing.rangeIndex]=r}),'Save range');}
function bookingsPage(){return `<section class="card"><h2>Booking review queue</h2>${filters([filterInput('q','Booking / advertiser'),filterSelect('status','Status',['Pending Review','Approved','Active','Rejected','Rejected (Timeout)','Completed'])])}<div id="rows"></div></section>`;}
function bookingRows(){return table(['Booking','Advertiser','Product / targeting','Locked price','Review deadline','Status',''],db.bookings.filter(b=>matches(b)&&(!view.status||view.status==='All'||b.status===view.status)).sort((a,b)=>a.deadline.localeCompare(b.deadline)).map(b=>[b.id,esc(b.account),esc(slotName(db.slots.find(s=>s.id===b.slot))),money(b.price),b.deadline+' · 09:00 JST',badge(b.status),btn('Review',`bookingDetail('${b.id}')`)]));}
function bookingDetail(id){const b=db.bookings.find(b=>b.id===id),s=db.slots.find(s=>s.id===b.slot),late=b.start<NOW,expired=b.deadline<NOW;drawer('Booking '+id,`<div class="drawer-body"><div class="between"><strong>${esc(b.account)}</strong>${badge(b.status)}</div><h3>Submitted creative</h3><div class="preview"><img src="${b.creative}" alt="${esc(b.title)} submitted banner"><div class="preview-caption"><strong>${esc(b.title)}</strong><p>${esc(b.copy)}</p></div></div><h3>Booking details</h3>${table(['Field','Submitted value'],[['Advertiser',esc(b.account)],['Ad product',products[s.product]],['Target object',esc(b.title)+(b.destination==='property'?' · Property PR-204':' · Own profile')],['Destination',`<a href="#" onclick="event.preventDefault();destinationPreview('${b.id}')">YUUSHI / ${b.destination} / ${esc(b.account.toLowerCase().replaceAll(' ','-'))}</a>`],['Targeting scope',esc(s.scope)],['Start',b.start],['Fixed end',b.end],['Locked price',money(b.price)],['Submitted',b.submitted+' · 09:00 JST'],['Review deadline',b.deadline+' · 09:00 JST']])}${b.status==='Pending Review'?(expired?'<p class="alert danger">Review deadline has passed. Approval is unavailable; investigate the overdue booking.</p>':late?'<p class="alert warn">The requested start date has passed. Approval starts delivery now; the original end date and full locked price remain unchanged. Lost days are not extended or compensated.</p>':'<p class="alert info">Approval charges the locked price and schedules the campaign for its original dates.</p>'):''}${b.reason?`<p>Rejection reason: ${esc(b.reason)}</p>`:''}<h3>Destination checks</h3><p>Owned by advertiser · On-platform destination · ${s.available?'Target inventory available':'Target unavailable'}</p>${b.status==='Pending Review'&&!expired?`<div class="row">${btn('Reject',`rejectBooking('${id}')`)}${s.available?btn('Approve',`approveBooking('${id}')`,'primary'):''}</div>`:''}</div>`);}
function destinationPreview(id){const b=db.bookings.find(b=>b.id===id);review('Destination preview',`<h3>${esc(b.title)}</h3><p>YUUSHI ${esc(b.destination)} · Owned by ${esc(b.account)}</p><p>${esc(b.copy)}</p>`,()=>{},'Close preview');}
function approveBooking(id){const b=db.bookings.find(b=>b.id===id);review('Approve '+id,`<p>${esc(b.account)} will be charged <strong>${money(b.price)}</strong>.</p><p>Delivery: ${b.start<NOW?NOW:b.start} → ${b.end}. The original end date remains fixed.</p><p>After approval, cancellation and refund are unavailable.</p>`,()=>decideBooking(id,'Approved'),'Approve & charge');}
function rejectBooking(id){review('Reject '+id,`${select('reason','Reason',['','Creative quality','Inappropriate content','Slot occupied','Incorrect targeting','Other'],'','id="rejectReason" onchange="document.querySelector(\'#otherReason\').hidden=this.value!==\'Other\'"')}<div id="otherReason" hidden>${textArea('other','Additional explanation','')}</div>`,()=>{const r=$('#rejectReason').value,t=$('#otherReason textarea').value.trim();if(!r||r==='Other'&&!t)throw Error('Select a reason and explain Other.');decideBooking(id,'Rejected',r==='Other'?'Other: '+t:r)},'Reject booking');}
function decideBooking(id,status,reason=''){const b=db.bookings.find(b=>b.id===id);if(b.status!=='Pending Review'||b.deadline<NOW)throw Error('This booking is no longer available for review. Reload its current state.');const before=clone(b);b.status=status==='Approved'&&b.start<=NOW?'Active':status;b.reason=reason;const hold=db.transactions.find(t=>t.object===id&&t.event==='Authorization');if(hold)hold.status='Resolved';db.transactions.push({id:'TX-'+Date.now(),engine:'Advertising',account:b.account,date:NOW,event:status==='Approved'?'Capture':'Release',amount:b.price,object:id,status:'Succeeded',reason:''});log(status+' booking','Advertising',id,before,b,reason);persist();closeEditor(true);render();}
function objectFor(engine,id){return (engine==='Subscription'?db.plans:engine==='Cart'?db.addons:db.slots).find(o=>o.id===id)}
function objectLabel(engine,id){const o=objectFor(engine,id);return o?(engine==='Advertising'?slotName(o):o.name):id}
function currentPrice(r){const o=objectFor(r.engine,r.object);return r.engine==='Subscription'?o.price:r.engine==='Cart'?o.variants[0].price:o.rate}
function recommendations(){view.engine??='Subscription';return tabs([['Subscription','Plans'],['Cart','Add-ons'],['Advertising','Advertising']].map(([k,v])=>[k,v])).replaceAll("view.tab=","view.engine=")+`<section class="card"><div class="between"><h2>${esc(view.engine)} recommendations</h2>${btn('Thresholds & guardrails',`ruleEditor('${view.engine}')`)}</div><div id="rows"></div></section>`;}
function recommendationRows(){return table(['Object / scope','Current','Recommended','Confidence','State',''],db.recommendations.filter(r=>r.engine===view.engine).map(r=>[esc(objectLabel(r.engine,r.object)),money(currentPrice(r)),money(r.price),r.confidence,badge(r.status),btn('Review',`recommendationDetail('${r.id}')`)]));}
const ruleLabels={increase:'Maximum increase per cycle · %',annual:'Maximum cumulative increase / 12 months · %',cooldown:'Cooldown · days',decrease:'Maximum decrease per cycle · %',strongConversion:'Strong conversion · %',weakConversion:'Weak conversion · %',renewal:'High renewal acceptance · %',churn:'Churn override · % for two months',minCycles:'Minimum complete observation cycles',minViews:'Minimum views / impressions',minPurchases:'Minimum subscriptions / purchases / bookings',strongCart:'Strong add-to-cart · %',repeat:'Repeat purchase · %',abandonment:'High abandonment · %',highOccupancy:'Sustained high occupancy · %',lowOccupancy:'Low occupancy · %',waitlist:'Waitlist pressure · accounts'};
Object.assign(ruleLabels,{upgradeInflow:'Strong upgrade inflow · %',noPurchasesDays:'No recent purchases · days',cancellation:'High cancellation / lower-tier migration · %',cancellationWindow:'Cancellation observation · days',strongMonths:'Strong signal observation · months',weakMonths:'Weak signal observation · months',renewalCycles:'Renewal observation · cycles',weakCart:'Weak add-to-cart · %',observationMonths:'Signal observation · months',repeatWindow:'Repeat-purchase observation · days',tierHigh:'Tier A demand index at or above',tierLow:'Tier C demand index below',concurrent:'Concurrent bookings signal',highMonths:'High occupancy observation · months',lowMonths:'Low occupancy observation · months',minPeers:'Minimum peer slots',trafficWeight:'Traffic score weight · %',demandWeight:'Demand score weight · %',qualityWeight:'Quality score weight · %',peerWeight:'Peer comparison weight · %',historicalWeight:'Historical comparison weight · %'});
function ruleEditor(engine){editing={kind:'rules',old:clone(db.rules[engine]),engine};drawer(engine+' pricing controls',form(Object.entries(db.rules[engine]).map(([k,v])=>field(k,ruleLabels[k],v,'number',`required min="0" step="0.1" ${ruleLabels[k].includes('%')?'max="100"':''}`)).join('')));}
function recommendationDetail(id){const r=db.recommendations.find(r=>r.id===id),o=objectFor(r.engine,r.object),guard=db.rules[r.engine],current=currentPrice(r),change=(r.price/current-1)*100,ad=r.engine==='Advertising';const evidence=r.engine==='Subscription'?[['Observation period','1 Jun – 31 Aug 2026 · 3 complete cycles'],['Plan screen views','1,200'],['New subscriptions','216'],['Conversion by month','17% / 18% / 19%'],['Renewal acceptance','92% / 94% · last two cycles'],['Churn by month','4% / 5%'],['Upgrade inflow','12%'],['Payment failure rate','1.2%'],['Peer group','Agency plans only'],['Peer median / range','¥28,000 / ¥12,000–¥60,000']]:r.engine==='Cart'?[['Observation period','1 Jul – 31 Aug 2026 · 2 complete months'],['Catalog views','800'],['Adds to cart','184'],['Add-to-cart rate','23%'],['Checkout completion','78%'],['Abandonment','22%'],['Repeat purchase','29%'],['Payment failures','2%'],['Peer group','Additional Listing Slots variants only'],['Peer median / range','¥5,000 / ¥4,500–¥6,000 per 5-listing monthly equivalent']]:[['Observation period','1 Jun – 31 Aug 2026 · 3 complete months'],['Impressions','42,000 / 46,000 / 51,000'],['Clicks / CTR','1,112 / 0.8%'],['Occupancy by month','88% / 91% / 93%'],['Bookings','9 completed packages'],['Concurrent bookings','4'],['Waitlist pressure','3 advertisers at observation end'],['Current waitlist',o.waitlist.length+' advertisers'],['Peer group',o.product<2?'None — self-historical only':'Static Banner pages · 3 slots'],['Comparison basis',o.product<2?'Self-historical only':'Self-historical fallback: fewer than 5 eligible peers'],['Historical median / range',money(current)+' / '+money(current*.9)+'–'+money(current*1.05)]];
 drawer('Pricing recommendation '+id,`<div class="drawer-body"><h3>${esc(objectLabel(r.engine,r.object))}</h3>${badge(r.status)}${table(['Decision input','Value'],[['Current price',money(current)],['Recommended price',money(r.price)],['Change',change.toFixed(1)+'%'],['Confidence',r.confidence],...evidence,['Last price change',r.last],['Allowed increase / decrease',guard.increase+'% / '+guard.decrease+'%'],['12-month increase used / allowed',r.annualChange+'% / '+guard.annual+'%'],['Cooldown',guard.cooldown+' days']])}${r.engine==='Subscription'?impact(o):'<p>Existing purchases and locked bookings retain their agreed prices.</p>'}${r.status==='Pending Review'?`<h3>Effective date</h3>${field('effective','Applies to new purchases from','2026-10-02','date',`min="${NOW}" id="effective"`)}${ad?field('through','Advertising price through','2026-10-31','date','id="through"'):''}<div class="row">${btn('Reject',`rejectRecommendation('${id}')`)}${btn('Review approval',`approveRecommendation('${id}')`,'primary')}</div><p id="formError" role="alert" class="error"></p>`:''}</div>`);}
function rejectRecommendation(id){const r=db.recommendations.find(r=>r.id===id);review('Reject recommendation','<p>The current price will remain unchanged.</p>',()=>commit('Rejected recommendation',r.engine,r.id,r,{...r,status:'Rejected'},()=>r.status='Rejected'),'Reject');}
function approveRecommendation(id){const r=db.recommendations.find(r=>r.id===id),o=objectFor(r.engine,r.object),g=db.rules[r.engine],change=(r.price/currentPrice(r)-1)*100,effective=$('#effective').value,end=$('#through')?.value;if(!effective||effective<NOW)return fail('Choose today or a future effective date.');if(change>g.increase+1e-8||-change>g.decrease+1e-8||r.annualChange+Math.max(0,change)>g.annual+1e-8||Date.parse(effective)-Date.parse(r.last)<g.cooldown*864e5)return fail('Outside the current guardrails or cooldown. Review pricing controls; approval is blocked.');if(r.engine==='Advertising'&&(!end||end<effective||db.bookings.some(b=>b.slot===o.id&&['Pending Review','Approved','Active'].includes(b.status)&&b.start<=end&&b.end>effective)||o.ranges.some(x=>x.start<=end&&x.end>=effective)))return fail('Choose an unreserved range that does not overlap a configured price range.');review('Approve price recommendation',`<p>${esc(objectLabel(r.engine,r.object))}: ${money(currentPrice(r))} → ${money(r.price)} from ${effective}.</p>${r.engine==='Subscription'?impact(o):'<p>Future purchases only; existing prices remain unchanged.</p>'}`,()=>{if(r.status!=='Pending Review')throw Error('Recommendation is no longer pending.');const before=clone(r);r.status=effective===NOW?'Applied':'Approved';r.effective=effective;r.end=end||'';if(r.engine==='Advertising')o.ranges.push({start:effective,end,rate:r.price,capacity:o.capacity,mode:o.mode,cutoff:''});else if(effective===NOW){if(r.engine==='Subscription')o.price=r.price;else o.variants[0].price=r.price}else o.scheduledPrice={date:effective,price:r.price};log('Approved recommendation',r.engine,r.id,before,r);persist();closeEditor(true);render()},'Approve');}
function dateFilters(){return [field('from','From',view.from||'2026-09-01','date','onchange="view.from=this.value;renderRows()"'),field('to','Through',view.to||'2026-09-30','date','onchange="view.to=this.value;renderRows()"')]}
function inPeriod(t){return t.date>=(view.from||'2026-09-01')&&t.date<=(view.to||'2026-09-30')}
function recognized(t){return t.status==='Succeeded'&&['Charge','Capture'].includes(t.event)}
function revenue(){return `<section class="card"><h2>Revenue reporting period</h2>${filters(dateFilters())}<div id="rows"></div></section>`;}
function revenueRows(){const tx=db.transactions.filter(t=>recognized(t)&&inPeriod(t)),engines=['Subscription','Cart','Advertising'];return `<div class="grid4">${[...engines,'Total'].map(e=>`<div class="stat"><div class="k">${e}</div><div class="v">${money(tx.filter(t=>e==='Total'||t.engine===e).reduce((a,t)=>a+t.amount,0))}</div></div>`).join('')}</div><p class="small">All recognized transactions in the selected sample period. Authorizations and releases are excluded.</p>${engines.map(engine=>{const rows=tx.filter(t=>t.engine===engine),keys=[...new Set(rows.map(t=>engine==='Advertising'?products[db.slots.find(s=>s.id===db.bookings.find(b=>b.id===t.object)?.slot)?.product]||'Unknown':t.object))];return `<h3>${engine}</h3>${table(['Product / plan / add-on','Transactions','Revenue',''],keys.map(k=>{const group=rows.filter(t=>engine==='Advertising'?products[db.slots.find(s=>s.id===db.bookings.find(b=>b.id===t.object)?.slot)?.product]===k:t.object===k);return [esc(engine==='Advertising'?k:objectLabel(engine,k)),group.length,money(group.reduce((a,t)=>a+t.amount,0)),btn('Drill down',`revenueDetail('${engine}','${k}')`)]}))}`}).join('')}`;}
function revenueDetail(engine,key){const tx=db.transactions.filter(t=>recognized(t)&&inPeriod(t)&&t.engine===engine&&(engine==='Advertising'?products[db.slots.find(s=>s.id===db.bookings.find(b=>b.id===t.object)?.slot)?.product]===key:t.object===key));drawer('Revenue · '+(engine==='Advertising'?key:objectLabel(engine,key)),`<div class="drawer-body">${engine==='Advertising'?table(['Placement / filter','Amount','Booking'],tx.map(t=>{const b=db.bookings.find(b=>b.id===t.object),s=db.slots.find(s=>s.id===b.slot);return [esc(s.scope),money(t.amount),link(5,b.id,b.id)]})):''}${transactionTable(tx)}</div>`);}
function transactionTable(rows){return table(['ID / date','Engine / object','Account','Event','Amount','Status / reason',''],rows.map(t=>[esc(t.id)+'<br>'+t.date,esc(t.engine)+'<br>'+esc(t.object),esc(t.account),esc(t.event),money(t.amount),badge(t.status)+(t.reason?'<br>'+esc(t.reason):''),btn('Details',`transactionDetail('${t.id}')`)]));}
function transactionDetail(id){const t=db.transactions.find(t=>t.id===id);drawer('Transaction '+id,`<div class="drawer-body">${table(['Field','Value'],Object.entries(t).map(([k,v])=>[esc(k),esc(v)]))}<p>${t.engine==='Advertising'?link(5,t.object,'Open booking'):link(t.engine==='Subscription'?1:3,t.object,'Open commercial object')}</p></div>`);}
function audit(){return `<section class="card"><h2>Read-only activity history</h2>${filters([...dateFilters(),filterSelect('actor','Actor',[...new Set(db.audit.map(a=>a.actor))]),filterSelect('action','Action',[...new Set(db.audit.map(a=>a.action))]),filterSelect('engine','Engine',['Subscription','Cart','Advertising']),filterInput('q','Object / text')])}<div id="rows"></div></section>`;}
function auditRows(){return table(['Date','Actor','Action','Engine','Object',''],db.audit.filter(a=>inPeriod(a)&&matches(a)&&['actor','action','engine'].every(k=>!view[k]||view[k]==='All'||view[k]===a[k])).map(a=>[a.date,esc(a.actor),esc(a.action),a.engine,esc(a.object),btn('Before / after',`auditDetail('${a.id}')`)]));}
function auditDetail(id){const a=db.audit.find(a=>a.id===id);drawer('Audit '+id,`<div class="drawer-body"><p>${esc(a.actor)} · ${a.date} · ${esc(a.action)}</p>${diff(a.before,a.after)}<p>Reason: ${esc(a.reason||'Not required for this action')}</p></div>`);}
function incidents(){const out=[];db.transactions.filter(t=>t.event==='Authorization'&&t.status==='Pending').forEach(t=>{const b=db.bookings.find(b=>b.id===t.object);if(!b)out.push({type:'Orphaned authorization',transaction:t.id,object:t.object,account:t.account});else if(b.status==='Pending Review'&&b.deadline<NOW)out.push({type:'Overdue review authorization',transaction:t.id,object:b.id,account:b.account})});db.transactions.filter(t=>t.event==='Capture').forEach(t=>{const b=db.bookings.find(b=>b.id===t.object);if(b&&t.amount!==b.price)out.push({type:'Charge / locked price mismatch',transaction:t.id,object:b.id,account:b.account})});return out;}
function operations(){view.tab??='monitor';return tabs([['monitor','Operations Monitor'],['transactions','Transactions & Reconciliation'],['visibility','Performance Visibility']])+(view.tab==='visibility'?`<section class="card"><h2>Buyer performance visibility</h2><p>Agency and Supportal advertising · global setting</p>${badge(db.settings.visible?'Visible · impressions, clicks and CTR':'Hidden · campaign status, dates and budget only')}<p>${btn(db.settings.visible?'Hide detailed figures':'Show detailed figures','visibilityReview()','primary')}</p></section>`:view.tab==='transactions'?`<section class="card"><h2>Reconciliation</h2>${table(['Incident','Count',''],['Overdue review authorization','Orphaned authorization','Charge / locked price mismatch'].map(type=>{const n=incidents().filter(i=>i.type===type).length;return [type,n,n?btn('View incidents',`incidentDetail('${type}')`):badge('Reconciled')]}))}</section><section class="card"><h2>Transactions</h2>${filters([...dateFilters(),filterSelect('engine','Engine',['Subscription','Cart','Advertising']),filterSelect('account','Account',[...new Set(db.transactions.map(t=>t.account))]),filterSelect('status','Status',['Succeeded','Failed','Pending','Resolved']),filterSelect('reason','Failure reason',['Card declined','Insufficient funds']),filterInput('q','Transaction / object')])}<div id="rows"></div></section>`:monitor(false));}
function operationsRows(){return transactionTable(db.transactions.filter(t=>inPeriod(t)&&matches(t)&&['engine','account','status','reason'].every(k=>!view[k]||view[k]==='All'||view[k]===t[k])))}
function visibilityReview(){const next=!db.settings.visible;review(next?'Reveal detailed performance?':'Hide detailed performance?',`<p>${next?'All Agency and Supportal advertisers will see actual impressions, clicks and CTR.':'All Agency and Supportal advertisers will see campaign status, dates and locked budget only.'}</p>`,()=>commit('Changed performance visibility','Advertising','Global visibility',{visible:db.settings.visible},{visible:next},()=>db.settings.visible=next),next?'Reveal figures':'Hide figures',next);}
function incidentDetail(type){drawer(type,`<div class="drawer-body">${table(['Account','Object','Transaction'],incidents().filter(i=>i.type===type).map(i=>[esc(i.account),link(5,i.object,i.object),btn(i.transaction,`transactionDetail('${i.transaction}')`)]))}</div>`);}
function monitor(dashboard){const pendingBooks=db.bookings.filter(b=>b.status==='Pending Review'),failed=db.transactions.filter(t=>t.status==='Failed'&&t.date>='2026-09-08'),total=db.transactions.filter(t=>recognized(t)&&t.date>='2026-09-01').reduce((a,t)=>a+t.amount,0);return `<div class="grid4">${[[money(total),'Revenue this month',7,''],[pendingBooks.length,'Bookings awaiting review',5,''],[failed.length,'Failed payments · 7 days',10,'failed'],[incidents().length,'Reconciliation incidents',10,'transactions']].map(([n,l,s,id])=>`<div class="stat"><div class="k">${link(s,id,l)}</div><div class="v">${n}</div></div>`).join('')}</div><section class="card" style="margin-top:18px"><h2>Immediate review · campaign delivery</h2><p>AD-10231 · Urban Estate · 0 of 20,000 estimated impressions. Platform traffic is normal.</p>${btn('Review delivery incident',"deliveryDetail()")}</section><div class="grid2"><section class="card"><h2>Ad review deadlines</h2>${table(['Booking','Deadline',''],pendingBooks.map(b=>[b.id,b.deadline,link(5,b.id,'Review booking')]))}</section><section class="card"><h2>Renewal confirmations at risk</h2>${table(['Account','Plan','Cycle ends',''],[['Kanto Realty','Gold','2026-09-18',btn('Details',"renewalDetail('Kanto Realty')")],['Tokyo Law Partners','Gold — Law','2026-09-21',btn('Details',"renewalDetail('Tokyo Law Partners')")]].filter(r=>(Date.parse(r[2])-Date.parse(NOW))/864e5<=db.settings.riskDays))}</section><section class="card"><h2>Failed payments</h2>${table(['Account','Failure',''],failed.map(t=>[esc(t.account),esc(t.reason),link(10,t.id,'Review transaction')]))}</section><section class="card"><h2>Stale failed cart items</h2>${table(['Account','Item','State',''],[['Green Estate','Additional Listing Slots','8 days · removal not completed',btn('Investigate',"staleDetail()")]])}</section></div>${dashboard?'':btn('Configure monitor thresholds',"settingsEditor('monitor')")}`;}
function deliveryDetail(){drawer('Delivery incident · AD-10231',`<div class="drawer-body"><p class="alert danger">Immediate review required · No delivery while platform traffic is normal.</p>${table(['Metric','Observed'],[['Account','Urban Estate'],['Placement','Static Banner · Agency Search'],['Observation','14–15 Sep 2026'],['Slot impressions delivered','0'],['Platform page views','12,480'],['Estimated package impressions','20,000'],['Schedule','1 Sep – 1 Oct 2026']])}${link(5,'AD-10231','Open campaign booking')}<p>No refund, credit or extension applies.</p></div>`);}
function renewalDetail(account){details('Renewal risk · '+account,{Account:account,Plan:account==='Kanto Realty'?'Gold':'Gold — Law','Current terms':'Preserved until cycle end','Renewal confirmation':'Not confirmed','Cycle ends':account==='Kanto Realty'?'2026-09-18':'2026-09-21','Without confirmation':'Returns to baseline at cycle end'})}
function staleDetail(){details('Failed cart item · Green Estate',{Item:'Additional Listing Slots ×5',Failed:'2026-09-07',Reason:'Insufficient funds','Expected removal':'2026-09-14','Observed state':'Removal incomplete · operational incident',Transaction:'TX-F2'})}
function render(){const views={1:plans,2:requests,3:addons,4:inventory,5:bookingsPage,6:recommendations,7:revenue,8:()=>monitor(true),9:audit,10:operations};$('#app').innerHTML=views[screen]();renderRows();}
function renderRows(){const target=$('#rows');if(!target)return;if(view.from&&view.to&&view.from>view.to){target.innerHTML='<p class="error" role="alert">The reporting end date must be on or after the start date.</p>';return}const rows={1:planRows,2:requestRows,3:addonRows,4:inventoryRows,5:bookingRows,6:recommendationRows,7:revenueRows,9:auditRows,10:operationsRows};target.innerHTML=rows[screen]();}
$('#overlay').onclick=()=>closeEditor();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#confirm').open&&$('#editor').classList.contains('open')){e.preventDefault();closeEditor()}if(e.key==='Tab'&&$('#editor').classList.contains('open')&&!$('#confirm').open){const nodes=[...$('#editor').querySelectorAll('button,input,select,textarea,a')].filter(n=>!n.disabled&&n.getClientRects().length),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
render();
const object=new URLSearchParams(location.search).get('object');if(object){if(screen===1&&db.plans.some(p=>p.id===object))editPlan(object);else if(screen===2&&object==='tiers'){view.tab='tiers';render()}else if(screen===3&&db.addons.some(a=>a.id===object))editAddon(object);else if(screen===4&&db.slots.some(s=>s.id===object))editSlot(object);else if(screen===5&&db.bookings.some(b=>b.id===object))bookingDetail(object);else if(screen===10){view.tab='transactions';if(object==='failed'){view.status='Failed';view.from='2026-09-08'}render();if(db.transactions.some(t=>t.id===object))transactionDetail(object);}}
