"""Rebuild the read-only BA catalog from all sheets of the Agency workbook."""
from pathlib import Path
import json, zipfile, xml.etree.ElementTree as ET
ROOT = Path(__file__).resolve().parents[1]
NS = {'m': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
with zipfile.ZipFile(ROOT / 'YUUSHI_Agency_Dashboard_Function_Spec_v2 (1).xlsx') as z:
    shared = []
    if 'xl/sharedStrings.xml' in z.namelist():
        shared = [''.join(e.itertext()) for e in ET.fromstring(z.read('xl/sharedStrings.xml'))]
    sheets = []
    for name in ('sheet1', 'sheet2', 'sheet3'):
        rows = []
        for row in ET.fromstring(z.read('xl/worksheets/' + name + '.xml')).findall('.//m:row', NS):
            cells = {}
            for c in row:
                key = ''.join(x for x in c.attrib['r'] if x.isalpha())
                if c.attrib.get('t') == 'inlineStr':
                    value = ''.join(t.text or '' for t in c.findall('.//m:t', NS))
                else:
                    v = c.find('m:v', NS)
                    value = v.text if v is not None else ''
                    if c.attrib.get('t') == 's': value = shared[int(value)]
                cells[key] = value
            rows.append(cells)
        sheets.append(rows)
    functions = []
    module = ''
    for row in sheets[0]:
        if not row.get('A', '').isdigit(): continue
        module = row.get('B') or module
        functions.append(dict(no=int(row['A']), module=module, title=row.get('C', ''), definition=row.get('D', ''), formula=row.get('E', ''), charts=row.get('F', ''), period=row.get('G', ''), source=row.get('H', ''), notes=row.get('I', '')))
    assert [r['no'] for r in functions] == list(range(1, 352))
    scope=json.loads((ROOT/'dashboard-tools/approved-metrics.json').read_text())
    functions=[r for r in functions if r['no'] not in scope['removed']]
    payload = dict(functions=functions, moduleScope=sheets[1][2:], scopeDecisions=sheets[2][2:])
    (ROOT / 'agency-dashboard-catalog.js').write_text('// Generated by dashboard-tools/build_catalog.py; no business records.\nwindow.AgencyDashboardSpec = ' + json.dumps(payload, ensure_ascii=False, separators=(',', ':')) + ';\n')
    print('Built scope-filtered catalog:', len(functions), 'function/structure entries; workbook rows are not automatically approved.')
