/* Source: OVERVIEW.xlsx, SVC AnalyticsReports and Automated Alert. */
window.OverviewSpec = {
  "metrics": [
    {
      "id": "r5",
      "row": 5,
      "page": "KPI Dashboard",
      "title": "Alert Bar (Real-time)",
      "definition": "",
      "calculation": "",
      "chart": "",
      "period": "",
      "outOfScope": false
    },
    {
      "id": "r6",
      "row": 6,
      "page": "KPI Dashboard",
      "title": "Unresponded Inquiries",
      "definition": "Count of unanswered chats from users to admin",
      "calculation": "Count of chats with status = unresponded",
      "chart": "Number badge (red)",
      "period": "Real-time",
      "outOfScope": false
    },
    {
      "id": "r7",
      "row": 7,
      "page": "KPI Dashboard",
      "title": "Property Complaints (Unprocessed)",
      "definition": "Count of unprocessed property complaints",
      "calculation": "Count of complaints with status = unprocessed",
      "chart": "Number badge (red)",
      "period": "Real-time",
      "outOfScope": false
    },
    {
      "id": "r8",
      "row": 8,
      "page": "KPI Dashboard",
      "title": "Pending Ad Approvals",
      "definition": "Count of banner and featured listing ads awaiting review",
      "calculation": "Count of ads with status = pending review",
      "chart": "Number badge (yellow)",
      "period": "Real-time",
      "outOfScope": false
    },
    {
      "id": "r9",
      "row": 9,
      "page": "KPI Dashboard",
      "title": "Fraud Detections",
      "definition": "Count of auto-detected fraudulent access and anomalies",
      "calculation": "Count of fraud flags with status = unhandled",
      "chart": "Number badge (red)",
      "period": "Real-time",
      "outOfScope": false
    },
    {
      "id": "r10",
      "row": 10,
      "page": "KPI Dashboard",
      "title": "Payment Errors",
      "definition": "Count of billing failures and chargebacks",
      "calculation": "Count of Stripe payment error statuses",
      "chart": "Number badge (red)",
      "period": "Real-time",
      "outOfScope": false
    },
    {
      "id": "r11",
      "row": 11,
      "page": "KPI Dashboard",
      "title": "Pending Agent Reviews",
      "definition": "Count of new agents awaiting approval",
      "calculation": "Count of agents with status = pending",
      "chart": "Number badge (yellow)",
      "period": "Real-time",
      "outOfScope": false
    },
    {
      "id": "r12",
      "row": 12,
      "page": "KPI Dashboard",
      "title": "System Status (Real-time)",
      "definition": "",
      "calculation": "",
      "chart": "",
      "period": "",
      "outOfScope": false
    },
    {
      "id": "r13",
      "row": 13,
      "page": "KPI Dashboard",
      "title": "API Status",
      "definition": "API server operational status",
      "calculation": "Health check API response verification",
      "chart": "Green/Yellow/Red badge",
      "period": "Real-time",
      "outOfScope": false
    },
    {
      "id": "r14",
      "row": 14,
      "page": "KPI Dashboard",
      "title": "DB Status",
      "definition": "Database operational status",
      "calculation": "DB connection check and response speed",
      "chart": "Green/Yellow/Red badge",
      "period": "Real-time",
      "outOfScope": false
    },
    {
      "id": "r15",
      "row": 15,
      "page": "KPI Dashboard",
      "title": "Payment Gateway Status",
      "definition": "Stripe operational status",
      "calculation": "Stripe API status check",
      "chart": "Green/Yellow/Red badge",
      "period": "Real-time",
      "outOfScope": false
    },
    {
      "id": "r16",
      "row": 16,
      "page": "KPI Dashboard",
      "title": "Error Log Count",
      "definition": "System error count in the past 24 hours",
      "calculation": "Error log count over past 24 hours",
      "chart": "Number",
      "period": "Past 24 hours",
      "outOfScope": false
    },
    {
      "id": "r17",
      "row": 17,
      "page": "KPI Dashboard",
      "title": "KPI Cards (Today + Day-on-Day)",
      "definition": "",
      "calculation": "",
      "chart": "",
      "period": "",
      "outOfScope": false
    },
    {
      "id": "r18",
      "row": 18,
      "page": "KPI Dashboard",
      "title": "Total Users",
      "definition": "Total registered users (customer/agent breakdown)",
      "calculation": "Count of all accounts excluding withdrawn users",
      "chart": "Number card",
      "period": "Cumulative",
      "outOfScope": false
    },
    {
      "id": "r19",
      "row": 19,
      "page": "KPI Dashboard",
      "title": "Active Users DAU/WAU/MAU",
      "definition": "DAU: today, WAU: 7 days, MAU: 30 days unique logins (toggle by user type)",
      "calculation": "DAU=daily unique logins, WAU=7-day unique, MAU=30-day unique",
      "chart": "Number card (toggle button)",
      "period": "DAU/WAU/MAU toggle",
      "outOfScope": false
    },
    {
      "id": "r20",
      "row": 20,
      "page": "KPI Dashboard",
      "title": "Avg Session Time",
      "definition": "Average site dwell time by customer and agent",
      "calculation": "Average of (session end time - start time) by user type",
      "chart": "Number card",
      "period": "Selected period average",
      "outOfScope": false
    },
    {
      "id": "r21",
      "row": 21,
      "page": "KPI Dashboard",
      "title": "Today's Revenue",
      "definition": "Total Stripe payment completions for the day",
      "calculation": "Sum of completed payment transactions for the day",
      "chart": "Number card + day-on-day %",
      "period": "Today",
      "outOfScope": false
    },
    {
      "id": "r22",
      "row": 22,
      "page": "KPI Dashboard",
      "title": "MTD Revenue",
      "definition": "Total Stripe payment completions for the current month",
      "calculation": "Cumulative sum of completed payment transactions from the 1st of the current month to today",
      "chart": "Number card + month-on-month %",
      "period": "Real-time (Cumulative)",
      "outOfScope": false
    },
    {
      "id": "r23",
      "row": 23,
      "page": "KPI Dashboard",
      "title": "MRR (Monthly Recurring Revenue)",
      "definition": "Total revenue from active subscriptions for the current month",
      "calculation": "Active subscriptions × plan unit price, summed",
      "chart": "Number card + month-on-month %",
      "period": "Current month",
      "outOfScope": false
    },
    {
      "id": "r24",
      "row": 24,
      "page": "KPI Dashboard",
      "title": "Total Listed Properties",
      "definition": "Total number of currently listed properties",
      "calculation": "Count of properties with status = published",
      "chart": "Number card + day-on-day",
      "period": "Cumulative (current)",
      "outOfScope": false
    },
    {
      "id": "r25",
      "row": 25,
      "page": "KPI Dashboard",
      "title": "Today's Inquiries",
      "definition": "Number of inquiries generated today",
      "calculation": "Count of inquiry transactions for the day",
      "chart": "Number card + day-on-day",
      "period": "Today",
      "outOfScope": false
    },
    {
      "id": "r26",
      "row": 26,
      "page": "KPI Dashboard",
      "title": "Target Setting",
      "definition": "Total revenue, revenue by category (subscription, sponsored banner, sponsored listing, appraisal referral, add-on options), number of users, number of subscriptions, number of property listings. Shows percentage of target achieved. Targets can be set for different time priods",
      "calculation": "",
      "chart": "",
      "period": "",
      "outOfScope": false
    },
    {
      "id": "r27",
      "row": 27,
      "page": "KPI Dashboard",
      "title": "Graph Area (Scroll)",
      "definition": "",
      "calculation": "",
      "chart": "",
      "period": "",
      "outOfScope": false
    },
    {
      "id": "r28",
      "row": 28,
      "page": "KPI Dashboard",
      "title": "Revenue Trend",
      "definition": "Monthly revenue by category (subscription, sponsored banner, sponsored listing, appraisal referral, add-on options)",
      "calculation": "Monthly sum of Stripe completions per category",
      "chart": "Stacked bar chart",
      "period": "Past 12 months",
      "outOfScope": false
    },
    {
      "id": "r29",
      "row": 29,
      "page": "KPI Dashboard",
      "title": "User Trend",
      "definition": "New registrations and DAU trend by user type",
      "calculation": "Daily new registration count and daily unique login count",
      "chart": "Line chart",
      "period": "Past 30 days",
      "outOfScope": false
    },
    {
      "id": "r30",
      "row": 30,
      "page": "KPI Dashboard",
      "title": "Listing Trend",
      "definition": "Listing count trend by property type",
      "calculation": "Daily count of listed properties by type tag",
      "chart": "Line chart",
      "period": "Past 30 days",
      "outOfScope": false
    },
    {
      "id": "r31",
      "row": 31,
      "page": "KPI Dashboard",
      "title": "Listing Trend",
      "definition": "Listing count trend by city",
      "calculation": "Daily count of listed properties by type tag",
      "chart": "Line chart",
      "period": "Past 30 days",
      "outOfScope": false
    },
    {
      "id": "r32",
      "row": 32,
      "page": "KPI Dashboard",
      "title": "Inquiry & Deal Trend",
      "definition": "Daily trend of inquiry and deal counts",
      "calculation": "Daily inquiry transactions and agent-reported deal count",
      "chart": "Bar chart",
      "period": "Past 30 days",
      "outOfScope": false
    },
    {
      "id": "r33",
      "row": 33,
      "page": "Analytics & Reports (Common)",
      "title": "Common Filter Definition",
      "definition": "Definition / Description:\nFilters applied across all metrics in the Analytics & Reports section from No.28 onward. Displayed as a persistent filter bar at the top of each analytics screen. Filter selections are retained during screen transitions. Default values apply when no selection is made. Filters consist of the following 8 axes using a 2-stage selection method.\n \nStage 2 options expand after Stage 1 is selected.\nFilter Axis 1: Transaction Type (Stage 1)\nAll / For Sale / For Rent / New Development\nFilter Axis 2: Property Group (Stage 2 - expands after Axis 1 selection)\nWhen \"For Sale\" selected: Group 1 (Single Unit) / Group 2 (Whole Building) / Group 3 (Land)\nWhen \"For Rent\" selected: Group 4 (Rental Properties)\nWhen \"New Development\" selected: Group 5 (New Development Apartments) / Group 6 (New Development Houses)\nWhen \"All\" selected: Group 1 to 6\nAfter selecting a group, sub-types can be selected (multiple selection allowed).\nExample: Group 1 sub-types: Apartment / Tower Mansion / Retail Unit / Office Unit / Factory & Warehouse Unit / Resort Apartment & Condo Hotel Unit\n\nFilter Axis 3: Period Unit\nDaily / Weekly / Monthly / Quarterly / Yearly / Custom (specify start and end date)\n\nFilter Axis 4: Comparison Axis\nNone / vs Previous Day / vs Previous Month / vs Previous Quarter / vs Previous Year or Custom Timeframe\n\nFilter Axis 5: Area\nStage 1: All Japan / Prefecture (multiple selection allowed)\nStage 2: After prefecture selected: City / Ward / Town (multiple selection allowed)\n\nFilter Axis 6: Station & Railway Line\nStage 1: Select railway line\nStage 2: After line selected: Station / Walking distance range (multiple selection allowed)\n\nFilter Axis 7: Property Detail Attributes\nBuilding Structure (SRC / RC / Steel / Lightweight Steel / Wooden / Other) / Floor Plan / Building Age Range / Floor Area Range / Price Range (multiple selection allowed, based on BA sheet definitions)\n\nFilter Axis 8: User Type\nAll / Members Only / Non-Members Only / Members vs Non-Members (side-by-side comparison)",
      "calculation": "ｰ",
      "chart": "Filter bar (fixed display at top of each analytics screen)",
      "period": "Applied to all metrics from No.28 onward",
      "outOfScope": false
    },
    {
      "id": "r35",
      "row": 35,
      "page": "Analytics ｰ Content Performance",
      "title": "Page Views by Section",
      "definition": "Trend of page views per site section. Sections include: Homepage, Property Search Results, Property Detail, Area Guides (by prefecture / by neighborhood), Article Content, Company Info, and static pages such as Terms & FAQ.",
      "calculation": "Daily PV count aggregated by URL or page category tag.",
      "chart": "Line chart (multiple series by section) / Bar chart (section comparison)",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r36",
      "row": 36,
      "page": "Analytics ｰ Content Performance",
      "title": "Unique Visitors by Section",
      "definition": "Number of unique visitors per section, excluding duplicate views within the same session.",
      "calculation": "Daily count of unique sessions per section.",
      "chart": "Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r37",
      "row": 37,
      "page": "Analytics ｰ Content Performance",
      "title": "IMP / CL / CTR by Section",
      "definition": "Impressions, clicks, and click-through rate per content section. Primarily measures clicks on internal links and CTA buttons within articles and Area Guides.",
      "calculation": "CTR = CL ÷ IMP × 100. Click logs for CTAs and internal links per section are aggregated.",
      "chart": "Bar chart / Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r38",
      "row": 38,
      "page": "Analytics ｰ Content Performance",
      "title": "CV / CVR by Section",
      "definition": "Number of conversions (member registrations and property inquiries) and CVR attributed to each content section. Measures conversions originating from content.",
      "calculation": "CV = number of sessions that completed a defined action (registration or inquiry) after viewing the section. CVR = CV ÷ section CL × 100.",
      "chart": "Bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r39",
      "row": 39,
      "page": "Analytics ｰ Content Performance",
      "title": "Avg Time on Page by Section",
      "definition": "Average time users spend on each section or page.",
      "calculation": "Average of (session exit time − entry time) per section.",
      "chart": "Bar chart (section comparison)",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r40",
      "row": 40,
      "page": "Analytics ｰ Content Performance",
      "title": "Bounce Rate by Section",
      "definition": "Bounce rate per section: percentage of sessions where the user viewed only one page before leaving.",
      "calculation": "Bounced sessions ÷ total sessions × 100.",
      "chart": "Bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r42",
      "row": 42,
      "page": "Analytics - End User Statistics",
      "title": "New Registration Trend",
      "definition": "Daily/weekly/monthly new customer registrations",
      "calculation": "Count by registration date",
      "chart": "Bar / Line chart",
      "period": "Custom period (default: past 30 days)",
      "outOfScope": false
    },
    {
      "id": "r43",
      "row": 43,
      "page": "Analytics - End User Statistics",
      "title": "Cumulative Registered User Trend",
      "definition": "Trend of cumulative customer registrations",
      "calculation": "Cumulative count from registration date onward",
      "chart": "Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r44",
      "row": 44,
      "page": "Analytics - End User Statistics",
      "title": "DAU/WAU/MAU",
      "definition": "Active customer user trend. For Registered Users and Unregistered Users",
      "calculation": "DAU=daily unique logins, WAU=7-day unique, MAU=30-day unique",
      "chart": "Line chart (3 lines)",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r45",
      "row": 45,
      "page": "Analytics - End User Statistics",
      "title": "Avg Session Time",
      "definition": "Average site dwell time for customers/Average viewing time per listing. For Registered Users and Unregistered Users",
      "calculation": "Average of (session end - start time)",
      "chart": "Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r46",
      "row": 46,
      "page": "Analytics - End User Statistics",
      "title": "Distribution by Nationality / Country",
      "definition": "Distribution of customer nationality and country of residence",
      "calculation": "Count by nationality and country of residence field",
      "chart": "Pie / Bar chart",
      "period": "Cumulative (current) and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r47",
      "row": 47,
      "page": "Analytics - End User Statistics",
      "title": "Member vs Non-Member (Guest) Behavior Comparison Analysis, and total behaviour analysis",
      "definition": "Section 1: Composition\nDisplays session count and ratio of members vs non-members as a stacked bar chart. Registration rate (CVR) is overlaid as a line chart.\n\nSection 2: Behavior Comparison (side-by-side on the same chart)\nThe following behavioral metrics are displayed side-by-side for members and non-members to compare content and property category interest.\nPage views by page type (property search results, property detail, area guide, articles, static pages)\nBreakdown of viewed properties by transaction type (For Sale, For Rent, New Development)\nBreakdown of viewed properties by property group (Group 1 to 6)\nSearch condition trends (area, price range, floor plan, building age)\nKeep (saved property) count and trends of saved properties (count of most saved property, count/trend of most saved properties in which areas, count/trend of most saved properties with which property attributes)\nAverage session duration and average number of properties viewed\nExit pages and bounce rate\n\nSection 3: Funnel Comparison\nCV rate at each step of the funnel (visit → property view → Keep → inquiry → closing) displayed side-by-side for members and non-members in a single funnel chart.",
      "calculation": "Section 1: Registered user sessions = sessions with a member ID (logged-in state). Non-registered user sessions = total sessions minus registered user sessions. Registration CVR = new account registrations completed within the period ÷ total sessions × 100.\nSection 2: Each behavior log is classified by presence or absence of member ID, then aggregated by page type, transaction type, property group, search conditions, etc. Non-members are identified via cookie or session-based tracking (note: duplicate counting of the same individual may occur).\nSection 3: CV rate at each funnel step = number completing the step ÷ number completing the previous step × 100. Calculated independently for members and non-members.",
      "chart": "Section 1: Stacked bar chart with registration rate (%) overlaid as a line chart.\nSection 2: Bar charts and pie charts with side-by-side display for members and non-members (metric toggle supported).\nSection 3: Funnel chart with side-by-side display for members and non-members.",
      "period": "Default set to \"Past 30 Days",
      "outOfScope": false
    },
    {
      "id": "r48",
      "row": 48,
      "page": "Analytics - End User Statistics",
      "title": "Distribution by Age / Gender",
      "definition": "Distribution of customer age groups and gender",
      "calculation": "Count by age group and gender field",
      "chart": "Stacked bar chart",
      "period": "Cumulative (current) and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r49",
      "row": 49,
      "page": "Analytics - End User Statistics",
      "title": "Distribution by Language / Device",
      "definition": "Distribution by language and device (PC/smartphone/tablet)",
      "calculation": "Count by language setting and UA device detection",
      "chart": "Pie chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r50",
      "row": 50,
      "page": "Analytics - End User Statistics",
      "title": "Acquisition Channel Analysis",
      "definition": "Registrations by acquisition channel at first registration",
      "calculation": "Count by selected acquisition channel at registration",
      "chart": "Pie / Bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r51",
      "row": 51,
      "page": "Analytics - End User Statistics",
      "title": "Access by Country Heatmap",
      "definition": "Distribution of customer access by country (from IP address)",
      "calculation": "IP address → country detection → count by country",
      "chart": "World map heatmap",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r52",
      "row": 52,
      "page": "Analytics - End User Statistics",
      "title": "Behavior Metrics Trend",
      "definition": "Trend of searches (buy/rent/sell), property views, saves, and inquiries",
      "calculation": "Daily count of each behavior log type",
      "chart": "Line chart (multiple metrics)",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r53",
      "row": 53,
      "page": "Analytics - End User Statistics",
      "title": "Behavior Metrics Trend",
      "definition": "Statistics of searches (property type, location/station, apartment no. of bedrooms, house no. of bedrooms, size, price range)",
      "calculation": "Daily count of each behavior log type",
      "chart": "",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r54",
      "row": 54,
      "page": "Analytics - End User Statistics",
      "title": "Site-wide Funnel Metrics Trend",
      "definition": "Monthly trend of five site-wide funnel metrics displayed in a single chart: total sessions, property views (CL), saves (Keep), inquiries (CV), and deals. Provides a top-level overview of the entire conversion funnel.",
      "calculation": "Monthly total for each metric. Displayed alongside month-on-month and year-on-year percentage change.",
      "chart": "Line chart (5 metrics as multiple series). Each metric can be toggled ON/OFF individually.",
      "period": "Monthly / Custom period (default: past 12 months)",
      "outOfScope": false
    },
    {
      "id": "r55",
      "row": 55,
      "page": "Analytics - End User Statistics",
      "title": "Dormant User Count",
      "definition": "Customers who have not logged in for 30+ days",
      "calculation": "Count of accounts where last login was 30+ days ago",
      "chart": "Number / Line chart",
      "period": "Current / Trend",
      "outOfScope": false
    },
    {
      "id": "r56",
      "row": 56,
      "page": "Analytics - End User Statistics",
      "title": "Withdrawal Trend",
      "definition": "Monthly withdrawal count trend",
      "calculation": "Count by withdrawal date",
      "chart": "Bar chart",
      "period": "Monthly / Custom period  ",
      "outOfScope": false
    },
    {
      "id": "r57",
      "row": 57,
      "page": "Analytics - End User Statistics",
      "title": "Chat Message Statistics - End User",
      "definition": "Number of chats with agents, total number of messages with agents",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": false
    },
    {
      "id": "r58",
      "row": 58,
      "page": "Analytics - End User Statistics",
      "title": "Chat Message Statistics - End User",
      "definition": "Number of messages sent per End-User, total number of messages sent by End-Users (by users from different countries)",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": false
    },
    {
      "id": "r59",
      "row": 59,
      "page": "Analytics - End User Statistics",
      "title": "Chat Message Statistics - Agents",
      "definition": "Number of messages sent per Agent, total number of messages sent by Agents",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": false
    },
    {
      "id": "r60",
      "row": 60,
      "page": "Analytics - End User Statistics",
      "title": "Chat Message Statistics - Response Time",
      "definition": "Average response time by Agents (when message sent during Japan business hours, outside of Japan business hours)",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": false
    },
    {
      "id": "r61",
      "row": 61,
      "page": "Analytics - End User Statistics",
      "title": "AI Chat Statistics - Number",
      "definition": "Number of chats with our AI agent, number of messages with our AI agent",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": true
    },
    {
      "id": "r62",
      "row": 62,
      "page": "Analytics - End User Statistics",
      "title": "AI Chat Statistics - Topics",
      "definition": "Top topics and questions for our AI agent, how many chats lead to search property page, other pages in Yuushi",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": true
    },
    {
      "id": "r63",
      "row": 63,
      "page": "Analytics - End User Statistics",
      "title": "Chat Message Statistics - Memory",
      "definition": "Memory utilisation for chats per end-user and per-agent, and in total",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": true
    },
    {
      "id": "r64",
      "row": 64,
      "page": "Analytics - End User Statistics",
      "title": "Chat Message Statistics - Attachments",
      "definition": "Memory untilisation for chats due to attachments and number of attachments, per end-user and per agent, and in total",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": true
    },
    {
      "id": "r65",
      "row": 65,
      "page": "Analytics - End User Statistics",
      "title": "Chat Message Statistics - Videos",
      "definition": "Memory untilisation for chats due to videos and number of attachments, per end-user and per agent, and in total",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": true
    },
    {
      "id": "r66",
      "row": 66,
      "page": "Analytics - End User Statistics",
      "title": "Chat Message Statistics - blocks by End-Users",
      "definition": "Number of blocks by End-Users, which agents are most blocked",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": true
    },
    {
      "id": "r67",
      "row": 67,
      "page": "Analytics - End User Statistics",
      "title": "Chat Message Statistics - blocks by Agents",
      "definition": "Number of blocks by Agents, which end-users are most blocked",
      "calculation": "",
      "chart": "",
      "period": "Monthly / Custom period  ",
      "outOfScope": true
    },
    {
      "id": "r69",
      "row": 69,
      "page": "Analytics - Agent Statistics",
      "title": "New Registration Trend",
      "definition": "Daily/Weekly/Monthly new agent registrations",
      "calculation": "Count by registration date",
      "chart": "Bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r70",
      "row": 70,
      "page": "Analytics - Agent Statistics",
      "title": "DAU/WAU/MAU",
      "definition": "Active agent user trend",
      "calculation": "DAU=daily unique logins, WAU=7-day unique, MAU=30-day unique",
      "chart": "Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r71",
      "row": 71,
      "page": "Analytics - Agent Statistics",
      "title": "Subscription Plan Distribution",
      "definition": "Distribution of agents by subscription plan",
      "calculation": "Count by plan field",
      "chart": "Pie chart",
      "period": "Current and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r72",
      "row": 72,
      "page": "Analytics - Agent Statistics",
      "title": "Subscription Plan Listings Utilisation",
      "definition": "Percentage of agents using maximum listing slots",
      "calculation": "",
      "chart": "",
      "period": "Current and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r73",
      "row": 73,
      "page": "Analytics - Agent Statistics",
      "title": "Ad Adoption Rate",
      "definition": "Percentage of all agent accounts using at least one ad product, at least two ad products, at least 3 ad products",
      "calculation": "Agents using ads ÷ total agents × 100",
      "chart": "Number card / Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r74",
      "row": 74,
      "page": "Analytics - Agent Statistics",
      "title": "Ad Adoption Rate per agent",
      "definition": "Ad spend per agent (by location of agent, by property type)",
      "calculation": "",
      "chart": "",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r75",
      "row": 75,
      "page": "Analytics - Agent Statistics",
      "title": "Ad Type Usage Breakdown",
      "definition": "Usage share of each ad type among ad-using agents (sponsored, banner, featured listing, appraisal referral), breakdown by area and property type",
      "calculation": "Agents using each ad type ÷ total ad-using agents × 100",
      "chart": "Pie / Bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r76",
      "row": 76,
      "page": "Analytics - Agent Statistics",
      "title": "Option Product Usage Breakdown",
      "definition": "Monthly aggregation/display of \"number of purchasers, number of purchases, and revenue\" per option product (e.g., CRM Boost Package / Profile Enhancement Package [Basic/Standard/Premium] / Additional Listing Slots / Multi-user Account). A per-product drill-down of the existing \"Revenue Report (Option Purchases)\"",
      "calculation": "Per product: Purchasers = count of unique purchasing accounts; Purchases = count of purchase transactions; Revenue = monthly sum of completed Stripe payments",
      "chart": "Stacked bar chart (by product) + data table; CSV export",
      "period": "Monthly",
      "outOfScope": false
    },
    {
      "id": "r77",
      "row": 77,
      "page": "Analytics - Agent Statistics",
      "title": "Listing Count Distribution",
      "definition": "Distribution of listing counts per agent",
      "calculation": "Count of active listings per agent ID",
      "chart": "Bar chart (histogram)",
      "period": "Current and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r78",
      "row": 78,
      "page": "Analytics - Agent Statistics",
      "title": "Response Rate / Speed Distribution",
      "definition": "Response rate and avg response time per agent",
      "calculation": "Response rate = replies ÷ received × 100; Response speed = avg hours to reply",
      "chart": "Bar chart / Scatter plot",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r79",
      "row": 79,
      "page": "Analytics - Agent Statistics",
      "title": "Deal Count Trend",
      "definition": "Monthly deal count trend per agent (agent-reported, Phase 1)",
      "calculation": "Monthly count based on agent-reported deals",
      "chart": "Bar chart",
      "period": "Monthly and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r80",
      "row": 80,
      "page": "Analytics - Agent Statistics",
      "title": "Agent League Table",
      "definition": "Ranking by listing count, deal count, ad spend, total payments, and rating",
      "calculation": "Sort by period total for each metric",
      "chart": "Ranking table",
      "period": "Current month / Quarter / Annual and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r81",
      "row": 81,
      "page": "Analytics - Agent Statistics",
      "title": "Revenue Breakdown by Plan",
      "definition": "Revenue breakdown: agents per plan × unit price",
      "calculation": "Contracts per plan × monthly unit price, summed",
      "chart": "Stacked bar / Pie chart",
      "period": "Monthly and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r82",
      "row": 82,
      "page": "Analytics - Agent Statistics",
      "title": "Appraisal Request - Distribution Statistics",
      "definition": "Number of appraisal requests by End Users (total, by property type, by property location)",
      "calculation": "",
      "chart": "Line graphs / Pie Chart",
      "period": "Monthly and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r83",
      "row": 83,
      "page": "Analytics - Agent Statistics",
      "title": "Appraisal Request - Agents Registered",
      "definition": "Number of agents registered for appraisal requests (total, by area, by property type)",
      "calculation": "",
      "chart": "Line graphs / Pie Chart",
      "period": "Monthly and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r84",
      "row": 84,
      "page": "Analytics - Agent Statistics",
      "title": "Appraisal Request - Sent to Agents",
      "definition": "Number of appraisals requests sent to agents (total, by property type, by property location)",
      "calculation": "",
      "chart": "Line graphs / Pie Chart",
      "period": "Monthly and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r85",
      "row": 85,
      "page": "Analytics - Agent Statistics",
      "title": "Appraisal Request - Submitted by Agents",
      "definition": "Number of appraisals submitted by agents (total, by property type, by property location)",
      "calculation": "",
      "chart": "Line graphs / Pie Chart",
      "period": "Monthly and Custom Period",
      "outOfScope": true
    },
    {
      "id": "r86",
      "row": 86,
      "page": "Analytics - Agent Statistics",
      "title": "Appraisal Request - JPY Value of Appraisals",
      "definition": "Total JPY value of appraisals submitted (total, by property type, by property location)",
      "calculation": "",
      "chart": "Line graphs / Pie Chart",
      "period": "Monthly and Custom Period",
      "outOfScope": true
    },
    {
      "id": "r91",
      "row": 91,
      "page": "Analytics - Property Statistics",
      "title": "Listing Trend (by Type)",
      "definition": "Trend of active property listings. Filterable by transaction type, property group, and property detail attributes via the common filter.",
      "calculation": "Daily count of listed properties by type tag",
      "chart": "Line chart (multiple series)",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r92",
      "row": 92,
      "page": "Analytics - Property Statistics",
      "title": "Listings by Area",
      "definition": "Listing count by prefecture and municipality (City / Ward / District)",
      "calculation": "Count by prefecture and municipality from location field",
      "chart": "Heatmap / Bar chart",
      "period": "Default: current point in time. Period and comparison axis can be changed via common filter axes 3 and 4.",
      "outOfScope": false
    },
    {
      "id": "r93",
      "row": 93,
      "page": "Analytics - Property Statistics",
      "title": "Price Range Distribution",
      "definition": "Distribution of property count by price range. Price axis automatically switches based on transaction type selected in the common filter: sale price for For Sale, unit price for New Development, and monthly rent for For Rent.",
      "calculation": "Count by price range segments",
      "chart": "Bar chart (histogram)",
      "period": "Default: current point in time. Period and comparison axis can be changed via common filter axes 3 and 4.",
      "outOfScope": false
    },
    {
      "id": "r94",
      "row": 94,
      "page": "Analytics - Property Statistics",
      "title": "IMP Trend",
      "definition": "Total property impression trend across the entire site",
      "calculation": "Daily sum of IMP across all listed properties",
      "chart": "Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r95",
      "row": 95,
      "page": "Analytics - Property Statistics",
      "title": "CL Trend",
      "definition": "Total property click count trend across the entire site",
      "calculation": "Daily sum of CL across all listed properties",
      "chart": "Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r96",
      "row": 96,
      "page": "Analytics - Property Statistics",
      "title": "Keep (Save) Count Trend",
      "definition": "Total property save count trend across the entire site",
      "calculation": "Daily sum of Keep (save) actions across all properties",
      "chart": "Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r97",
      "row": 97,
      "page": "Analytics - Property Statistics",
      "title": "CTR",
      "definition": "Average click-through rate across the entire site",
      "calculation": "CTR = Total CL ÷ Total IMP × 100",
      "chart": "Line chart / Number",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r98",
      "row": 98,
      "page": "Analytics - Property Statistics",
      "title": "CV (Inquiry) Trend",
      "definition": "Total inquiry count trend across the entire site",
      "calculation": "Daily sum of CV (inquiries) across all properties",
      "chart": "Bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r99",
      "row": 99,
      "page": "Analytics - Property Statistics",
      "title": "CVR",
      "definition": "Average inquiry conversion rate across the entire site",
      "calculation": "CVR = Total CV ÷ Total CL × 100",
      "chart": "Line chart / Number",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r100",
      "row": 100,
      "page": "Analytics - Property Statistics",
      "title": "Deal Count Trend",
      "definition": "Monthly deal count trend",
      "calculation": "Monthly count by deal report date",
      "chart": "Bar chart",
      "period": "Default: monthly. Period unit (daily / weekly / monthly / quarterly / yearly / custom) and comparison axis (vs previous month, vs previous year, etc.) can be changed via common filter axes 3 and 4.",
      "outOfScope": false
    },
    {
      "id": "r101",
      "row": 101,
      "page": "Analytics - Property Statistics",
      "title": "Avg Listing Duration",
      "definition": "Average number of days from listing start to end",
      "calculation": "Average of (listing end date - listing start date)",
      "chart": "Number / Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r102",
      "row": 102,
      "page": "Analytics - Property Statistics",
      "title": "Listing End by Reason",
      "definition": "Count of listing ends by reason: YUUSHI deal / Sold on other channel / Seller took off market",
      "calculation": "Count by listing end reason field value",
      "chart": "Pie / Bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r103",
      "row": 103,
      "page": "Analytics - Property Statistics",
      "title": "Price Trend by Property / Building Type - Listing Price",
      "definition": "Average price trend by property group and sub-type. Price axis automatically switches based on transaction type in the common filter: sale price for For Sale, monthly rent for For Rent, and unit price for New Development.",
      "calculation": "Time-series average of price fields by property group and sub-type tag. Referenced price field automatically switches by transaction type: sale price for For Sale, monthly rent for For Rent, unit price for New Development.",
      "chart": "Line chart (multiple series)",
      "period": "Monthly / Quarterly / Annual toggle",
      "outOfScope": false
    },
    {
      "id": "r104",
      "row": 104,
      "page": "Analytics - Property Statistics",
      "title": "Price Trend by Property / Building Type - Sale Price vs Listing Price",
      "definition": "Trend of average listing price vs closing price by property group and sub-type. Display series automatically switches based on transaction type in the common filter. For Sale: listing price, closing price, price per sqm (/㎡). For Rent: monthly rent, monthly rent per sqm (/㎡/month). New Development: unit price, price per sqm (/㎡).",
      "calculation": "Time-series average of price fields by property group and sub-type tag. Referenced fields switch automatically by transaction type: listing price and closing price for For Sale, monthly rent for For Rent, unit price for New Development.",
      "chart": "Line chart (multiple series)",
      "period": "Monthly / Quarterly / Annual toggle",
      "outOfScope": false
    },
    {
      "id": "r105",
      "row": 105,
      "page": "Analytics - Property Statistics",
      "title": "Price Trend by Building Age",
      "definition": "Avg price trend by building age range",
      "calculation": "Time-series average of price by building age range",
      "chart": "Line chart",
      "period": "Default: monthly. Period unit (daily / weekly / monthly / quarterly / yearly / custom) and comparison axis (vs previous month, vs previous year, etc.) can be changed via common filter axes 3 and 4.",
      "outOfScope": false
    },
    {
      "id": "r107",
      "row": 107,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "Total Platform CPA",
      "definition": "Platform-wide true CPA across all revenue streams, segmented by conversion type.",
      "calculation": "・Inquiry CPA = Total Spend ÷ Total Inquiries\n ・Closing CPA = Total Spend ÷ Total Verified Closings",
      "chart": "Number card / Line chart (Toggle switch)",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r108",
      "row": 108,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "Subscription Revenue Trend by Plan",
      "definition": "Monthly revenue and active contract trends by subscription tier.",
      "calculation": "Monthly sum of active subscription counts and total revenue per plan type",
      "chart": "Stacked bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r109",
      "row": 109,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "Subscription Revenue Trend by Plan",
      "definition": "Monthly revenue and active contract trends by subscription tier. Different series for Japan as a whole and by prefecture, city",
      "calculation": "Monthly sum of active subscription counts and total revenue per plan type",
      "chart": "Stacked bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r110",
      "row": 110,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "Subscription Slot Utilization Rate",
      "definition": "Percentage of allocated listing slots currently utilized by agents.",
      "calculation": "(Number of Live Listings ÷ Total Purchased Listing Slots) × 100",
      "chart": "Gauge chart / Line chart",
      "period": "Monthly and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r111",
      "row": 111,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "Revenue Trend by Ad Type",
      "definition": "Monthly revenue trend by individual ad product category.",
      "calculation": "Monthly sum of Stripe completions per ad category (sponsored, banner, featured listing, appraisal referral)",
      "chart": "Stacked bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r112",
      "row": 112,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "Overall CPA (Subscription-based)",
      "definition": "Conversion cost efficiency for the monthly subscription model.",
      "calculation": "・Inquiry CPA = Sub Revenue ÷ Total Inquiries\n ・Closing CPA = Sub Revenue ÷ Total Closings",
      "chart": "Line chart / Number card",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r113",
      "row": 113,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "CPA by Ad Type",
      "definition": "Cost efficiency comparison across different ad products and tiers.",
      "calculation": "CPA per type = Total cost for type ÷ Total CV for type (Inquiries or Closings)",
      "chart": "Bar chart (Type comparison)",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r114",
      "row": 114,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "CPA by Placement / Page",
      "definition": "CPA comparison by specific page or position where ads appear.",
      "calculation": "CPA per page/position = Total cost for page ÷ Total CV for page (Inquiries or Closings)",
      "chart": "Bar chart (Page comparison)",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r115",
      "row": 115,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "IMP / CL / CTR / CV / CVR",
      "definition": "Platform-wide baseline ad performance and effectiveness metrics.",
      "calculation": "Total IMP, Total CL, CTR = CL÷IMP×100, Total CV, CVR = CV÷CL×100",
      "chart": "Line / Bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r116",
      "row": 116,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "Overall CPA (Ad-based)",
      "definition": "Platform-wide average cost per acquisition for optional paid ads.",
      "calculation": "・Inquiry CPA = Total Ad Spend ÷ Total Inquiries\n ・Closing CPA = Total Ad Spend ÷ Total Closings",
      "chart": "Number / Line chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r117",
      "row": 117,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "Ad Effectiveness by Agent",
      "definition": "Granular ad performance and spend analysis per individual agent.",
      "calculation": "Aggregate IMP, CL, CTR, CV, CVR, CPA, and total spend grouped by Agent ID",
      "chart": "Ranking table",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r118",
      "row": 118,
      "page": "Analytics - Revenue and Ad Performance",
      "title": "Appraisal Referral Analysis by Area",
      "definition": "Referral efficiency, billing, and budget caps segmented by geographic area.",
      "calculation": "Count by area tag, sum of billing, utilization = spend ÷ cap × 100, block count",
      "chart": "Bar chart / Heatmap",
      "period": "Monthly and Custom Period",
      "outOfScope": false
    },
    {
      "id": "r120",
      "row": 120,
      "page": "Analytics - Market Analysis",
      "title": "Avg Price Trend by Area and Property Type",
      "definition": "Average price trend by area. Price axis automatically switches based on transaction type in the common filter: sale price for For Sale, monthly rent for For Rent, and unit price for New Development. Area can be filtered using common filter axes 5 (Area) and 6 (Station & Railway Line).",
      "calculation": "Time-series average of price fields by area. Referenced price field automatically switches based on selected transaction type.",
      "chart": "Default: monthly. Period unit (monthly / quarterly / yearly / custom) and comparison axis (vs previous month, vs previous quarter, vs previous year) can be changed via common filter axes 3 and 4.",
      "period": "Monthly / Quarterly / Annual toggle, and custom period",
      "outOfScope": false
    },
    {
      "id": "r121",
      "row": 121,
      "page": "Analytics - Market Analysis",
      "title": "Area × Property Type × Performance",
      "definition": "Matrix display of which area/property type combinations have high IMP/Keep/CV",
      "calculation": "Aggregates total IMP, CL, Keep, CV, and CVR by the combination of axes selected in the common filter. When a comparison axis is selected, the prior period value is displayed alongside the current value.",
      "chart": "Heatmap / Matrix table",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r122",
      "row": 122,
      "page": "Analytics - Market Analysis",
      "title": "Popular Area Ranking",
      "definition": "Area ranking by high IMP, inquiry rate, and conversion rate",
      "calculation": "Sort by area total IMP, CVR, and conversion rate",
      "chart": "Ranking table",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r123",
      "row": 123,
      "page": "Analytics - Market Analysis",
      "title": "Popular Route & Station Ranking",
      "definition": "Route & station ranking by high IMP, inquiry rate, and conversion rate",
      "calculation": "Sort by area total IMP, CVR, and conversion rate",
      "chart": "Ranking table",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r124",
      "row": 124,
      "page": "Analytics - Market Analysis",
      "title": "Popularity by Station Distance",
      "definition": "IMP, inquiry rate, and conversion rate by walking time from station",
      "calculation": "Average of each metric by walking time range",
      "chart": "Bar chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r125",
      "row": 125,
      "page": "Analytics - Market Analysis",
      "title": "Popularity by Property Detail Attributes",
      "definition": "Building Structure (SRC / RC / Steel / Lightweight Steel / Wooden / Other) / Floor Plan / Building Age Range / Floor Area Range / Price Range (multiple selection allowed, based on BA sheet definitions)",
      "calculation": "",
      "chart": "",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r126",
      "row": 126,
      "page": "Analytics - Market Analysis",
      "title": "Popularity by Keyword",
      "definition": "Most searched keywords - Pets Allowed, Corner Unit, South Facing, Maisonette, Parking Lot, Bicycle Parking, Garden, Rooftop, Building Concierge (English Speaking), Condominium, All-electric, Fully Furnished, Designer Property, Quiet Residential Area",
      "calculation": "",
      "chart": "",
      "period": "Custom period",
      "outOfScope": true
    },
    {
      "id": "r127",
      "row": 127,
      "page": "Analytics - Market Analysis",
      "title": "Supply-Demand Statistics",
      "definition": "Supply-demand balance: inventory vs search volume by area and property type",
      "calculation": "Listings ÷ searches by area (supply-demand ratio)",
      "chart": "Bar chart / Heatmap",
      "period": "Default: monthly. Period unit (monthly / quarterly / yearly / custom) and comparison axis (vs previous month, vs previous year) can be changed via common filter axes 3 and 4.",
      "outOfScope": false
    },
    {
      "id": "r128",
      "row": 128,
      "page": "Analytics - Market Analysis",
      "title": "Access by Country & Time of Day",
      "definition": "Analysis of peak access hours by country for customers",
      "calculation": "Session count by country × time of day",
      "chart": "Heatmap (24h × country)",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r130",
      "row": 130,
      "page": "Cross Analysis",
      "title": "CV Funnel (End User × Property)",
      "definition": "CV rate at each step: view → save (Keep) → inquiry → deal",
      "calculation": "Count at each step ÷ count at previous step × 100",
      "chart": "Funnel chart",
      "period": "Custom period",
      "outOfScope": false
    },
    {
      "id": "r131",
      "row": 131,
      "page": "Cross Analysis",
      "title": "ROAS (Agent × Revenue)",
      "definition": "Ad spend to revenue efficiency per agent",
      "calculation": "ROAS = Revenue (deal amount) ÷ Ad spend × 100",
      "chart": "Ranking table / Scatter plot",
      "period": "Custom period",
      "outOfScope": true
    },
    {
      "id": "r132",
      "row": 132,
      "page": "Cross Analysis",
      "title": "Listing Completeness × Conversion Rate",
      "definition": "Correlation between listing completeness (photo count, description length, etc.) and conversion rate",
      "calculation": "Avg conversion rate by information completeness score",
      "chart": "Scatter plot",
      "period": "Custom period",
      "outOfScope": true
    },
    {
      "id": "r133",
      "row": 133,
      "page": "Cross Analysis",
      "title": "Plan × LTV (Retention Rate)",
      "definition": "Retention rate and LTV analysis by free vs paid plan",
      "calculation": "Churn rate per plan = cancellations ÷ contracts × 100; LTV = avg contract term × monthly unit price",
      "chart": "Line / Bar chart",
      "period": "Monthly and Custom Period",
      "outOfScope": true
    },
    {
      "id": "r134",
      "row": 134,
      "page": "Cross Analysis",
      "title": "Response Speed / Rate × Conversion Rate",
      "definition": "Correlation between agent response speed/rate and conversion rate",
      "calculation": "Avg conversion rate by response speed range and response rate range",
      "chart": "Scatter plot",
      "period": "Custom period",
      "outOfScope": true
    },
    {
      "id": "r135",
      "row": 135,
      "page": "Cross Analysis",
      "title": "Agent Rating × Conversion Rate",
      "definition": "Correlation between agent rating score and conversion rate",
      "calculation": "Avg conversion rate by rating score range",
      "chart": "Scatter plot",
      "period": "Custom period",
      "outOfScope": true
    },
    {
      "id": "r136",
      "row": 136,
      "page": "Cross Analysis",
      "title": "Risk Analysis",
      "definition": "Trend of illegal listing rate, fraud detection count, and refund rate",
      "calculation": "Illegal flags ÷ total listings × 100; Fraud detections; Refunds ÷ total payments × 100",
      "chart": "Line chart",
      "period": "Monthly and Custom Period",
      "outOfScope": true
    },
    {
      "id": "r137",
      "row": 137,
      "page": "Cross Analysis",
      "title": "CRM Marketing Effectiveness",
      "definition": "Measurement of CRM delivery open rate, click-through rate, and CV",
      "calculation": "In-platform: read÷sent×100→clicks÷read×100→CV\n Email: opens÷sent×100→clicks÷opens×100→CV",
      "chart": "Funnel chart",
      "period": "Per delivery campaign and custom period",
      "outOfScope": false
    },
    {
      "id": "r139",
      "row": 139,
      "page": "Report Management",
      "title": "Monthly Market Report Auto-generation",
      "definition": "Monthly auto-report of property sale price trend, rent trend, listing count, and deal count. Site revenue is managed separately in the revenue report.",
      "calculation": "Monthly aggregated values output in a standard format",
      "chart": "CSV / PDF",
      "period": "Monthly automatic, and custom period",
      "outOfScope": false
    },
    {
      "id": "r140",
      "row": 140,
      "page": "Report Management",
      "title": "Revenue Report",
      "definition": "Monthly revenue by category with month-on-month comparison. Categories: subscription (by plan/tier), add-on options, sponsored, banner (by placement location), featured listing, appraisal referral, option purchases.",
      "calculation": "Monthly Stripe aggregation per category and month-on-month calculation",
      "chart": "CSV",
      "period": "Monthly automatic, and custom period",
      "outOfScope": false
    },
    {
      "id": "r141",
      "row": 141,
      "page": "Report Management",
      "title": "User Report",
      "definition": "Periodic report: cumulative total users (by type), new registrations, dormant count, withdrawals, and net growth (new minus withdrawn) for the month.",
      "calculation": "Period aggregate for each metric",
      "chart": "CSV",
      "period": "Weekly / Monthly automatic and custom period",
      "outOfScope": false
    },
    {
      "id": "r142",
      "row": 142,
      "page": "Report Management",
      "title": "Operational Report",
      "definition": "Periodic report: Unresponded Inquiries, Property Complaints (Unprocessed), Pending Ad Approvals, Fraud Detections, Payment Errors, Pending Agent Reviews, Forgot passwords requests",
      "calculation": "",
      "chart": "",
      "period": "",
      "outOfScope": false
    },
    {
      "id": "r143",
      "row": 143,
      "page": "Report Management",
      "title": "Custom Report Builder",
      "definition": "Combine any axes, metrics, and periods for CSV export. Frequently used conditions can be saved as shortcuts.",
      "calculation": "Extract and export data based on selected metrics and filter conditions",
      "chart": "CSV",
      "period": "Manual (custom period)",
      "outOfScope": false
    },
    {
      "id": "r144",
      "row": 144,
      "page": "Report Management",
      "title": "Scheduled Report Delivery",
      "definition": "Auto email delivery for periodic reports (daily/weekly/monthly). Multiple recipient addresses supported.",
      "calculation": "Auto-send periodic reports at configured frequency to configured recipients",
      "chart": "-",
      "period": "Daily / Weekly / Monthly setting and custom period",
      "outOfScope": false
    },
    {
      "id": "r145",
      "row": 145,
      "page": "Report Management",
      "title": "Data Monetization Report",
      "definition": "CSV export of anonymized market data. Personal information is excluded.",
      "calculation": "Data output after personal information exclusion and anonymization",
      "chart": "CSV",
      "period": "Manual",
      "outOfScope": false
    },
    {
      "id": "r146",
      "row": 146,
      "page": "Cohort Analysis",
      "title": "User Registration Month Retention Rate",
      "definition": "Analyze retention and engagement trends by user registration month",
      "calculation": "Using the number of users registered in a given month as the baseline, calculate: (Users who logged in or performed key actions in each subsequent month ÷ Users registered in that month) × 100",
      "chart": "Cohort Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r147",
      "row": 147,
      "page": "Cohort Analysis",
      "title": "Agent Registration Month Retention Rate",
      "definition": "Analyze retention and engagement trends by agent registration month",
      "calculation": "Using the number of agents registered in a given month as the baseline, calculate: (Agents who logged in, listed properties, responded to inquiries, etc. ÷ Agents registered in that month) × 100",
      "chart": "Cohort Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r148",
      "row": 148,
      "page": "Cohort Analysis",
      "title": "Post-Plan Change Retention Rate",
      "definition": "Analyze retention rates after plan upgrades/downgrades",
      "calculation": "Using users who changed plans as the baseline, calculate: (Users who remain active within a specified period after the plan change ÷ Users who changed plans) × 100",
      "chart": "Cohort Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r149",
      "row": 149,
      "page": "Cohort Analysis",
      "title": "Post-First Inquiry Retention Rate",
      "definition": "Analyze retention after a user's first inquiry submission",
      "calculation": "Using users who submitted their first inquiry as the baseline, calculate: (Users who logged in again or performed another action within a specified period after the inquiry ÷ Users who submitted their first inquiry) × 100",
      "chart": "Cohort Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r150",
      "row": 150,
      "page": "Cohort Analysis",
      "title": "Post-Ad Usage Retention Rate",
      "definition": "Analyze retention and LTV after starting ad usage",
      "calculation": "Using agents who started advertising as the baseline, calculate: (Agents who renewed contracts or repurchased advertisements within a specified period ÷ Agents who started advertising) × 100",
      "chart": "Cohort Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r151",
      "row": 151,
      "page": "Cohort Analysis",
      "title": "Post-First Contract Retention Rate",
      "definition": "Analyze retention after the first successful contract/transaction",
      "calculation": "Using users/agents who completed their first transaction as the baseline, calculate: (Users/agents who remain active within a specified period after the transaction ÷ Users/agents who completed their first transaction) × 100",
      "chart": "Cohort Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r152",
      "row": 152,
      "page": "Cohort Analysis",
      "title": "Cohort Comparison Analysis",
      "definition": "Compare cohorts by user type, area, and acquisition channel",
      "calculation": "Group users by registration month, user type, area, and acquisition channel, then compare retention rate, engagement rate, and LTV across groups",
      "chart": "Stacked Bar Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r153",
      "row": 153,
      "page": "Cohort Analysis",
      "title": "Cohort LTV Analysis",
      "definition": "Analyze LTV trends by registration month and subscription plan",
      "calculation": "Calculate average LTV by registration month and plan: Total revenue generated by the cohort ÷ Number of users/agents in the cohort",
      "chart": "Cohort Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r154",
      "row": 154,
      "page": "Cohort Analysis",
      "title": "Cohort Visualization",
      "definition": "Display monthly retention rates in heatmap format",
      "calculation": "Display registration month on the vertical axis and elapsed months on the horizontal axis, with retention rates visualized using color intensity",
      "chart": "Cohort Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r155",
      "row": 155,
      "page": "Cohort Analysis",
      "title": "Activation Event Analysis",
      "definition": "Analyze actions with high retention impact (first inquiry, ad usage, etc.)",
      "calculation": "Group users by whether they performed actions such as first inquiry, ad usage, or first transaction, then compare retention rates across groups",
      "chart": "Cohort Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r156",
      "row": 156,
      "page": "Churn Analysis",
      "title": "Monthly Churn Rate",
      "definition": "Analyze monthly churn rate trends",
      "calculation": "Calculate: (Number of cancellations during the month ÷ Number of active subscriptions at the beginning of the month) × 100",
      "chart": "Line Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r157",
      "row": 157,
      "page": "Churn Analysis",
      "title": "Churn Rate by Plan",
      "definition": "Compare churn rates across subscription plans",
      "calculation": "Calculate by plan: (Number of cancellations during the month ÷ Number of active subscriptions at the beginning of the month) × 100",
      "chart": "Horizontal Bar Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r158",
      "row": 158,
      "page": "Churn Analysis",
      "title": "Churn Rate by Area",
      "definition": "Analyze churn rates by region/area",
      "calculation": "Calculate by area: (Number of cancellations during the month ÷ Number of active subscriptions at the beginning of the month) × 100",
      "chart": "Horizontal Bar Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r159",
      "row": 159,
      "page": "Churn Analysis",
      "title": "Churn Rate by Usage Frequency",
      "definition": "Analyze churn by login frequency and usage activity",
      "calculation": "Calculate by login frequency/usage frequency segment: (Number of cancellations ÷ Number of active subscriptions in the segment) × 100",
      "chart": "Scatter Plot",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r160",
      "row": 160,
      "page": "Churn Analysis",
      "title": "Cancellation Reason Analysis",
      "definition": "Aggregate and analyze cancellation reasons by category",
      "calculation": "Aggregate cancellation reasons by category and calculate count and percentage",
      "chart": "Horizontal Bar Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r161",
      "row": 161,
      "page": "Churn Analysis",
      "title": "Pre-Churn Behavior Analysis",
      "definition": "Analyze user behavior during the 30 days before cancellation (reduced login frequency, ad suspension, etc.)",
      "calculation": "Analyze login frequency, inquiry volume, response rate, ad usage, and other activities during the 30 days prior to cancellation, then compare against normal behavior",
      "chart": "Time-Series Line Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r162",
      "row": 162,
      "page": "Churn Analysis",
      "title": "Churn Prediction Score",
      "definition": "Score and display churn likelihood",
      "calculation": "Assign weighted scores to indicators such as reduced login frequency, reduced response rate, ad suspension, and listing reduction, then calculate a churn risk score",
      "chart": "Ranked List",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r163",
      "row": 163,
      "page": "Churn Analysis",
      "title": "Threshold Alert Notification",
      "definition": "Notify CRM/sales teams when churn risk thresholds are exceeded",
      "calculation": "When a churn risk score exceeds a predefined threshold, identify the user/agent and notify the sales or CRM team",
      "chart": "Slack Notification",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r164",
      "row": 164,
      "page": "Churn Analysis",
      "title": "Churn Factor Analysis",
      "definition": "Analyze behavioral and attribute factors affecting churn",
      "calculation": "Analyze correlations and impact factors between churn and attributes such as login frequency, plan type, area, ad usage, and response rate",
      "chart": "Correlation Heatmap",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r165",
      "row": 165,
      "page": "Churn Analysis",
      "title": "Reactivation Rate Analysis",
      "definition": "Analyze re-subscription and re-registration rates after churn",
      "calculation": "Calculate: (Number of users who re-subscribed or re-registered after cancellation ÷ Number of cancelled users) × 100",
      "chart": "Stacked Bar Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r166",
      "row": 166,
      "page": "Search Analytics",
      "title": "Popular Search Condition Ranking",
      "definition": "Analyze rankings of search keywords and conditions",
      "calculation": "Rank search keywords, areas, price ranges, stations, property types, and other search conditions by search volume",
      "chart": "Horizontal Ranking Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r167",
      "row": 167,
      "page": "Search Analytics",
      "title": "Zero-Result Search Rate",
      "definition": "Analyze the percentage of searches returning zero results",
      "calculation": "Calculate: (Number of searches returning zero results ÷ Total number of searches) × 100",
      "chart": "Ranked List",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r168",
      "row": 168,
      "page": "Search Analytics",
      "title": "Search-to-Click Rate",
      "definition": "Analyze click-through rate from search results to property pages",
      "calculation": "Calculate: (Number of property detail clicks from search results ÷ Total number of searches) × 100",
      "chart": "Funnel Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r169",
      "row": 169,
      "page": "Search Analytics",
      "title": "Filter Usage Rate",
      "definition": "Analyze usage trends of search filters",
      "calculation": "Calculate: (Number of searches using filters ÷ Total number of searches) × 100",
      "chart": "Horizontal Bar Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r170",
      "row": 170,
      "page": "Search Analytics",
      "title": "Price Range Search Distribution",
      "definition": "Analyze searches by price range",
      "calculation": "Aggregate search volume by specified price range",
      "chart": "Histogram",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r171",
      "row": 171,
      "page": "Search Analytics",
      "title": "Area Search Distribution",
      "definition": "Analyze searches by geographic area",
      "calculation": "Aggregate search volume by prefecture, city, and area",
      "chart": "Heatmap",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r172",
      "row": 172,
      "page": "Search Analytics",
      "title": "Station Search Distribution",
      "definition": "Analyze searches by railway line/station",
      "calculation": "Aggregate search volume by railway line and station",
      "chart": "Ranking Table",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r173",
      "row": 173,
      "page": "Search Analytics",
      "title": "Search Exit Rate",
      "definition": "Analyze user drop-off rate after searches",
      "calculation": "Calculate: (Number of search sessions that ended without a property view or inquiry ÷ Total number of search sessions) × 100",
      "chart": "Drop-off Rate Line Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r174",
      "row": 174,
      "page": "Search Analytics",
      "title": "Supply Shortage Analysis",
      "definition": "Analyze shortages of properties and agents relative to search demand",
      "calculation": "Compare search demand with the number of available listings and active agents by area, station, and price range to identify supply shortages",
      "chart": "Heatmap",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r175",
      "row": 175,
      "page": "Search Analytics",
      "title": "Search Trend Analysis",
      "definition": "Analyze time-series trends in search conditions and areas",
      "calculation": "Aggregate search volume by keyword, area, and condition on a daily, weekly, and monthly basis, then analyze trends over time",
      "chart": "",
      "period": "",
      "outOfScope": true
    },
    {
      "id": "r176",
      "row": 176,
      "page": "Search Analytics",
      "title": "Trending Search Keywords",
      "definition": "Analyze rapidly increasing search keywords and areas",
      "calculation": "Compare recent search volume with historical averages and identify keywords or areas with the highest growth rates",
      "chart": "Line Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r177",
      "row": 177,
      "page": "Search Analytics",
      "title": "Search Heatmap",
      "definition": "Display search demand heatmaps by area",
      "calculation": "Visualize search demand by area using maps or matrix-based heatmaps",
      "chart": "Heatmap",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r178",
      "row": 178,
      "page": "Search Analytics",
      "title": "Dynamic Pricing Integration",
      "definition": "Reflect search demand data into pricing coefficients",
      "calculation": "Calculate a demand score using search volume, zero-result rate, listing volume, and conversion rate, then apply the score to pricing coefficients",
      "chart": "Geographic Heatmap",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r179",
      "row": 179,
      "page": "Search Analytics",
      "title": "AI Search Analytics",
      "definition": "Analyze AI-powered search and recommendation usage rates",
      "calculation": "Calculate AI search/recommendation usage rate: (Number of AI-powered searches ÷ Total searches) and effectiveness: (Conversions generated via AI search ÷ AI-powered searches)",
      "chart": "Comparison Bar Chart",
      "period": "Monthly and custom period",
      "outOfScope": true
    },
    {
      "id": "r180",
      "row": 180,
      "page": "Search Analytics",
      "title": "Search Suggestion Analytics",
      "definition": "Analyze suggestion usage and selection rates",
      "calculation": "Aggregate suggestion impressions, selections, and resulting searches, then calculate Suggestion Selection Rate = (Selections ÷ Impressions) × 100",
      "chart": "Sankey Diagram",
      "period": "Monthly and custom period",
      "outOfScope": true
    }
  ],
  "alerts": [
    {
      "id": "alert-1",
      "name": "High Volume Inquiries",
      "trigger": "Over 30 inquiries within 1 hours",
      "fraud": true,
      "target": "Customer"
    },
    {
      "id": "alert-2",
      "name": "Multi-Device Login",
      "trigger": "Logins from different countries/IPs/devices in a short time",
      "fraud": true,
      "target": "All Users"
    },
    {
      "id": "alert-3",
      "name": "Consecutive Failed Logins",
      "trigger": "Over 30 failed login attempts from the same IP per day.",
      "fraud": true,
      "target": "All Users"
    },
    {
      "id": "alert-4",
      "name": "Report Received",
      "trigger": "Receipt of a user report",
      "fraud": true,
      "target": "Customer / Agent"
    },
    {
      "id": "alert-5",
      "name": "Multiple Listing Violations",
      "trigger": "5 or more reported listings within 90 days",
      "fraud": false,
      "target": "Agent"
    },
    {
      "id": "alert-6",
      "name": "Consecutive Payment Failure",
      "trigger": "2 consecutive failures of auto-renewal payments",
      "fraud": true,
      "target": "Agent / Customer"
    },
    {
      "id": "alert-7",
      "name": "End of Free Trial",
      "trigger": "Trial ended + no application for paid subscription",
      "fraud": false,
      "target": "Agent"
    },
    {
      "id": "alert-8",
      "name": "Long-term Inactivity",
      "trigger": "No login for 90+ days",
      "fraud": false,
      "target": "Customer / Agent"
    },
    {
      "id": "alert-9",
      "name": "Dormancy",
      "trigger": "No login for 180+ days",
      "fraud": false,
      "target": "Customer / Agent"
    },
    {
      "id": "alert-10",
      "name": "New chat notification",
      "trigger": "On receipt of Admin chat",
      "fraud": false,
      "target": "Customer / Agent"
    },
    {
      "id": "alert-11",
      "name": "Schedule Alerts",
      "trigger": "When scheduled Admin date/time is reached",
      "fraud": false,
      "target": "Admin"
    },
    {
      "id": "alert-12",
      "name": "License Expiry Date",
      "trigger": "Expired License",
      "fraud": false,
      "target": "Agent"
    },
    {
      "id": "alert-13",
      "name": "Mass Reporting (Potential Abuse)",
      "trigger": "10 or more reports submitted within a 30-day period",
      "fraud": true,
      "target": "Customer / Agent"
    }
  ]
};
